// data.js — Structure des modules TSSR

const MODULES = [
  {
    id: 'numerisation',
    label: 'Numération',
    icon: '🔢',
    color: '#00ff88',
    desc: 'Systèmes de numération : binaire, octal, hexadécimal, conversions...',
    topics: [],
    outils: 'modules/numerisation/outils.html',
    cours: [
      {
        id: 'cours_optimise_claude',
        titre: 'Architecture des Données : Encodage, Systèmes de Numération et Logique Booléenne',
        sections: [
          { type: 'html-file', src: 'modules/numerisation/cours_optimise_claude.html' },
        ],
      },
    ],
    flashcards: [],
    qcm: [],
  },
  {
    id: 'reseaux',
    label: 'Réseaux',
    icon: '🌐',
    color: '#3b82f6',
    desc: 'Modèle OSI, TCP/IP, adressage IP, sous-réseaux, services réseau...',
    topics: ['OSI', 'TCP/IP', 'Adressage IP', 'VLAN', 'DNS', 'DHCP', 'Routage'],
    cours: [
      {
        id: 'modele-osi',
        titre: 'Modèle OSI — 7 Couches',
        sections: [],
      },
      {
        id: 'cours_reseaux',
        titre: 'Réseaux : OSI, TCP/IP, Adressage et Services',
        sections: [{ type: 'html-file', src: 'modules/reseaux/cours_reseaux.html' }],
      },
    ],
    flashcards: [],
    qcm: [],
    linux_cli: true,
    windows_cli: true,
  },
  {
    id: 'linux',
    label: 'Linux',
    icon: '🐧',
    color: '#00ff88',
    desc: 'Commandes, droits, services, filtrage, gestion de paquets...',
    topics: ['Système de fichiers', 'VIM', 'Droits', 'Processus', 'APT', 'Redirections'],
    cours: [
      {
        id: 'encyclopedie-linux',
        titre: 'Encyclopédie Linux — Formation TSSR',
        sections: [

          // 1. Installation & Philosophie
          { type: 'h2', content: '1. Installation &amp; Philosophie' },
          { type: 'p', content: 'Linux est un noyau open-source utilisé dans la majorité des serveurs, équipements réseau et systèmes embarqués. En formation TSSR, on travaille généralement sous Debian/Ubuntu dans une machine virtuelle (VirtualBox ou VMware).' },
          { type: 'info', content: '<strong>Virtualisation :</strong> une VM Linux s\'installe depuis une image ISO. On choisit la langue, le partitionnement (ext4 recommandé) et un utilisateur non-root dès l\'installation.' },
          { type: 'table', headers: ['Compte', 'Rôle', 'Invite de commande'], rows: [
            ['root', 'Super-administrateur, droits illimités', '<code>#</code>'],
            ['utilisateur', 'Compte courant, droits limités', '<code>$</code>'],
          ]},
          { type: 'warn', content: '<strong>Ne jamais travailler en root au quotidien.</strong> Utiliser <code>sudo</code> pour élever les privilèges ponctuellement.' },
          { type: 'code', content: 'sudo apt update          # exécute apt en tant que root\nsudo -i                  # ouvre un shell root (quitter avec exit)\nwhoami                   # affiche l\'utilisateur courant\nid                       # UID, GID et groupes' },

          // 2. Navigation & Système de fichiers
          { type: 'h2', content: '2. Navigation &amp; Système de fichiers' },
          { type: 'p', content: 'Linux utilise une arborescence unique enracinée en <code>/</code>. Pas de lettres de lecteur comme sous Windows : tout est monté sous la racine.' },
          { type: 'table', headers: ['Répertoire', 'Contenu'], rows: [
            ['<code>/</code>',     'Racine du système'],
            ['<code>/etc</code>',  'Fichiers de configuration système'],
            ['<code>/home</code>', 'Répertoires personnels des utilisateurs'],
            ['<code>/var</code>',  'Données variables (logs, bases, cache)'],
            ['<code>/bin</code>',  'Binaires essentiels (ls, cp, mv…)'],
            ['<code>/usr</code>',  'Applications installées'],
            ['<code>/tmp</code>',  'Fichiers temporaires (vidés au reboot)'],
            ['<code>/proc</code>', 'Pseudo-FS : infos noyau/processus en temps réel'],
          ]},
          { type: 'code', content: 'pwd                      # affiche le répertoire courant\nls                       # liste les fichiers\nls -l                    # format long (droits, taille, date)\nls -la                   # idem + fichiers cachés (commençant par .)\nls -lh                   # tailles lisibles (Ko, Mo)\ncd /etc                  # aller dans /etc\ncd ~                     # aller dans son home\ncd ..                    # remonter d\'un niveau\ncd -                     # revenir au répertoire précédent\ntree                     # arborescence graphique (si installé)' },
          { type: 'info', content: '<strong>Chemin absolu vs relatif :</strong> <code>/home/user/docs</code> est absolu (part de /). <code>../docs</code> est relatif (part du répertoire courant).' },

          // 3. Manipulation de fichiers
          { type: 'h2', content: '3. Manipulation de fichiers' },
          { type: 'code', content: 'mkdir dossier            # créer un répertoire\nmkdir -p a/b/c           # créer l\'arborescence complète\ntouch fichier.txt        # créer un fichier vide (ou mettre à jour la date)\ncp source dest           # copier un fichier\ncp -r src/ dest/         # copier un dossier (récursif)\nmv ancien nouveau        # déplacer ou renommer\nrm fichier               # supprimer un fichier\nrm -r dossier/           # supprimer un dossier et son contenu\nrm -rf dossier/          # idem, sans confirmation (dangereux)' },
          { type: 'warn', content: '<strong>rm -rf</strong> est irréversible. Il n\'y a pas de corbeille en ligne de commande. Vérifier deux fois avant d\'exécuter.' },
          { type: 'code', content: 'cat fichier.txt          # afficher le contenu\nless fichier.txt         # affichage page par page (q pour quitter)\nhead -n 5 fichier.txt    # 5 premières lignes\ntail -n 5 fichier.txt    # 5 dernières lignes\ntail -f /var/log/syslog  # suivre un fichier en temps réel\nwc -l fichier.txt        # compter les lignes\nfile fichier             # type du fichier' },

          // 4. Édition VIM
          { type: 'h2', content: '4. Édition VIM' },
          { type: 'p', content: 'VIM est l\'éditeur de texte en ligne de commande incontournable. Il fonctionne par modes : on ne tape pas directement comme dans un éditeur graphique.' },
          { type: 'table', headers: ['Mode', 'Description', 'Accès'], rows: [
            ['Normal',    'Navigation, copier/coller, suppression', 'Touche <code>Échap</code>'],
            ['Insertion', 'Saisie de texte',                        '<code>i</code> (avant curseur), <code>a</code> (après), <code>o</code> (nouvelle ligne)'],
            ['Commande',  'Sauvegarder, quitter, rechercher',       '<code>:</code> depuis le mode Normal'],
          ]},
          { type: 'steps', items: [
            { num: '1', title: 'Ouvrir un fichier',         code: 'vim fichier.txt' },
            { num: '2', title: 'Passer en mode insertion',  content: 'Appuyer sur <kbd>i</kbd>' },
            { num: '3', title: 'Écrire du texte',           content: 'Saisir normalement' },
            { num: '4', title: 'Revenir en mode normal',    content: 'Appuyer sur <kbd>Échap</kbd>' },
            { num: '5', title: 'Sauvegarder et quitter',    code: ':wq' },
          ]},
          { type: 'table', headers: ['Commande', 'Action'], rows: [
            ['<code>:w</code>',    'Sauvegarder'],
            ['<code>:q</code>',    'Quitter (si pas de modification)'],
            ['<code>:wq</code>',   'Sauvegarder et quitter'],
            ['<code>:q!</code>',   'Quitter sans sauvegarder (forcer)'],
            ['<code>/mot</code>',  'Rechercher "mot" (n = occurrence suivante)'],
            ['<code>dd</code>',    'Supprimer la ligne courante (mode normal)'],
            ['<code>yy</code>',    'Copier la ligne (yank)'],
            ['<code>p</code>',     'Coller après le curseur'],
            ['<code>u</code>',     'Annuler (undo)'],
            ['<code>Ctrl+r</code>','Rétablir (redo)'],
          ]},

          // 5. Droits Linux
          { type: 'h2', content: '5. Droits Linux' },
          { type: 'p', content: 'Chaque fichier a des droits pour 3 entités : le propriétaire (u), le groupe (g), et les autres (o). Les droits sont r (lecture), w (écriture), x (exécution).' },
          { type: 'table', headers: ['Droit', 'Lettre', 'Valeur octale'], rows: [
            ['Lecture',    'r', '4'],
            ['Écriture',   'w', '2'],
            ['Exécution',  'x', '1'],
            ['Aucun droit','—', '0'],
          ]},
          { type: 'info', content: '<strong>Lecture rapide de chmod :</strong> <code>755</code> = rwxr-xr-x (propriétaire : tout ; groupe et autres : lecture + exécution). <code>644</code> = rw-r--r-- (fichier de config type).' },
          { type: 'code', content: 'ls -l fichier.txt\n# -rw-r--r-- 1 alice staff 1024 juin  9 10:00 fichier.txt\n#  ^^^       ^\n#  droits    |— nb liens\n#  u=rw g=r o=r\n\nchmod 755 script.sh      # rwxr-xr-x\nchmod +x  script.sh      # ajouter exécution à tous\nchmod u+w fichier.txt    # ajouter écriture au propriétaire\nchmod o-r fichier.txt    # retirer lecture aux autres\n\nchown alice fichier.txt         # changer propriétaire\nchown alice:staff fichier.txt   # changer propriétaire et groupe\nchgrp staff fichier.txt         # changer groupe uniquement' },

          // 6. Redirections & Flux
          { type: 'h2', content: '6. Redirections &amp; Flux' },
          { type: 'table', headers: ['Flux', 'Numéro', 'Description'], rows: [
            ['stdin',  '0', 'Entrée standard (clavier par défaut)'],
            ['stdout', '1', 'Sortie standard (terminal par défaut)'],
            ['stderr', '2', 'Sortie d\'erreur (terminal par défaut)'],
          ]},
          { type: 'code', content: 'ls > liste.txt           # redirige stdout vers fichier (écrase)\nls >> liste.txt          # redirige stdout (ajoute)\nls 2> erreurs.txt        # redirige stderr vers fichier\nls > tout.txt 2>&1       # redirige stdout ET stderr\nls 2>/dev/null           # jeter les erreurs\ncat < fichier.txt        # stdin depuis fichier\ncommande1 | commande2    # pipe : stdout1 → stdin2\necho "texte" | wc -c    # compter les caractères via pipe' },
          { type: 'info', content: '<strong>Chaîner avec pipes :</strong> <code>cat /etc/passwd | grep bash | cut -d: -f1</code> — affiche les utilisateurs avec bash comme shell.' },

          // 7. Gestion processus & services
          { type: 'h2', content: '7. Gestion des processus &amp; services' },
          { type: 'h3', content: 'Processus' },
          { type: 'code', content: 'ps aux                   # liste tous les processus\nps aux | grep nginx      # filtrer par nom\ntop                      # moniteur interactif (q pour quitter)\nhtop                     # version améliorée (si installé)\nkill 1234                # envoyer SIGTERM au PID 1234\nkill -9 1234             # forcer la fin (SIGKILL)\npkill nginx              # tuer par nom\nkillall nginx            # tuer toutes les instances\nnohup cmd &              # lancer en arrière-plan, immunisé au logout' },
          { type: 'code', content: 'commande &               # lancer en arrière-plan\njobs                     # lister les tâches en arrière-plan\nfg %1                    # ramener la tâche 1 au premier plan\nbg %1                    # reprendre la tâche 1 en arrière-plan\nCtrl+Z                   # suspendre la commande en cours\nCtrl+C                   # interrompre la commande en cours' },
          { type: 'h3', content: 'Services (systemd)' },
          { type: 'code', content: 'systemctl status ssh              # état du service ssh\nsystemctl start  ssh             # démarrer\nsystemctl stop   ssh             # arrêter\nsystemctl restart ssh            # redémarrer\nsystemctl enable  ssh            # activer au démarrage\nsystemctl disable ssh            # désactiver au démarrage\nsystemctl list-units --type=service   # lister les services\njournalctl -u ssh                # logs du service ssh\njournalctl -f                    # suivre les logs en temps réel' },

          // 8. Filtrage & Traitement
          { type: 'h2', content: '8. Filtrage &amp; Traitement de texte' },
          { type: 'h3', content: 'grep — rechercher des lignes' },
          { type: 'code', content: 'grep "motif" fichier.txt         # lignes contenant "motif"\ngrep -i "motif" fichier.txt      # insensible à la casse\ngrep -r "motif" /etc/            # récursif dans un dossier\ngrep -v "motif" fichier.txt      # lignes NE contenant PAS "motif"\ngrep -n "motif" fichier.txt      # afficher les numéros de ligne\ngrep -c "motif" fichier.txt      # compter les occurrences\ngrep -E "^root|^alice" /etc/passwd  # regex étendue' },
          { type: 'h3', content: 'cut — extraire des colonnes' },
          { type: 'code', content: 'cut -d: -f1 /etc/passwd          # 1er champ, délimiteur :\ncut -d: -f1,3 /etc/passwd        # champs 1 et 3\ncut -c1-10 fichier.txt           # caractères 1 à 10 de chaque ligne' },
          { type: 'h3', content: 'sed — remplacer du texte' },
          { type: 'code', content: 'sed "s/ancien/nouveau/" fichier.txt    # remplace 1ère occurrence par ligne\nsed "s/ancien/nouveau/g" fichier.txt   # remplace toutes les occurrences\nsed -i "s/foo/bar/g" fichier.txt       # modifie le fichier en place\nsed "/^#/d" fichier.txt                # supprime les lignes commençant par #' },
          { type: 'h3', content: 'awk — traitement structuré' },
          { type: 'code', content: 'awk "{print $1}" fichier.txt      # affiche le 1er champ (séparateur espace)\nawk -F: "{print $1,$3}" /etc/passwd   # séparateur :, champs 1 et 3\nawk "$3 > 1000" /etc/passwd      # lignes où le champ 3 > 1000\nawk "END{print NR}" fichier.txt  # compter le nombre de lignes' },

          // 9. Gestion des paquets APT
          { type: 'h2', content: '9. Gestion des paquets — APT' },
          { type: 'p', content: 'APT (Advanced Package Tool) est le gestionnaire de paquets de Debian/Ubuntu. Il télécharge et installe les logiciels depuis des dépôts officiels.' },
          { type: 'steps', items: [
            { num: '1', title: 'Mettre à jour la liste des paquets', code: 'sudo apt update', why: 'Synchronise la liste locale avec les dépôts — à faire avant toute installation.' },
            { num: '2', title: 'Mettre à jour les paquets installés', code: 'sudo apt upgrade', why: 'Installe les nouvelles versions de tous les paquets existants.' },
            { num: '3', title: 'Installer un paquet',                code: 'sudo apt install vim',  why: 'Télécharge et installe vim et ses dépendances.' },
            { num: '4', title: 'Désinstaller un paquet',             code: 'sudo apt remove vim',   why: 'Supprime le paquet mais garde les fichiers de configuration.' },
            { num: '5', title: 'Désinstaller + config',              code: 'sudo apt purge vim',    why: 'Supprime le paquet ET ses fichiers de configuration.' },
            { num: '6', title: 'Nettoyer les paquets orphelins',     code: 'sudo apt autoremove',   why: 'Supprime les dépendances devenues inutiles.' },
          ]},
          { type: 'code', content: 'apt search nginx                 # rechercher un paquet\napt show nginx                   # informations sur un paquet\ndpkg -l | grep nginx             # vérifier si installé\ndpkg -L nginx                    # lister les fichiers du paquet\napt list --installed             # tous les paquets installés\napt-cache policy nginx           # version installée vs disponible' },
          { type: 'info', content: '<strong>Rappel :</strong> toujours faire <code>sudo apt update</code> avant <code>apt install</code>, sinon APT peut proposer une version obsolète.' },

        ],
      },
    ],
    flashcards: [],
    qcm: [],
    linux_cli: true,
    gameshell: true,
  },
  {
    id: 'linux-server',
    label: 'Serveur Linux',
    icon: '🐧',
    color: '#00e5a0',
    desc: 'Administration serveur Debian/Ubuntu, Apache, SSH, Samba, pare-feu...',
    topics: ['SSH', 'Apache', 'Samba', 'UFW', 'Cron', 'Logs'],
    linux_cli: true,
    cours: [
      {
        id: 'admin-linux-base',
        titre: 'Administration Serveur Linux — Les Fondamentaux',
        sections: [
          { type: 'h2', content: 'Gestion des utilisateurs' },
          { type: 'code', content: '# Créer un utilisateur avec home\nuseradd -m -s /bin/bash anthony\npasswd anthony\n\n# Ajouter au groupe sudo\nusermod -aG sudo anthony\n\n# Voir les groupes d\'un utilisateur\ngroups anthony\n\n# Supprimer un utilisateur\nuserdel -r anthony' },
          { type: 'h2', content: 'Gestion des services (systemd)' },
          { type: 'code', content: '# Démarrer / arrêter / redémarrer\nsystemctl start apache2\nsystemctl stop apache2\nsystemctl restart apache2\n\n# Activer au démarrage\nsystemctl enable apache2\n\n# Voir le statut détaillé\nsystemctl status apache2\n\n# Lister tous les services actifs\nsystemctl list-units --type=service --state=active' },
          { type: 'h2', content: 'Surveillance du système' },
          { type: 'code', content: '# Espace disque\ndf -h\n\n# Utilisation RAM\nfree -h\n\n# Charge CPU\ntop\nhtop  # plus lisible (apt install htop)\n\n# Processus d\'un service\nps aux | grep apache2\n\n# Logs système en temps réel\njournalctl -f\ntail -f /var/log/syslog' },
          { type: 'h2', content: 'Gestion des paquets (APT)' },
          { type: 'code', content: 'apt update && apt upgrade -y\napt install apache2 -y\napt remove apache2\napt autoremove\ndpkg -l | grep apache  # lister les paquets installés' },
          { type: 'h2', content: 'Planification des tâches (Cron)' },
          { type: 'code', content: '# Éditer la crontab de l\'utilisateur courant\ncrontab -e\n\n# Format : minute heure jour mois jour_semaine commande\n# Exemple : sauvegarde tous les jours à 2h00\n0 2 * * * /usr/local/bin/backup.sh >> /var/log/backup.log 2>&1\n\n# Lister les tâches planifiées\ncrontab -l' },
        ],
      },
      {
        id: 'services-reseau-linux',
        titre: 'Services Réseau Linux — SSH, Apache, Samba',
        sections: [
          { type: 'h2', content: 'SSH — Accès distant sécurisé' },
          { type: 'p', content: 'SSH (Secure Shell) permet l\'administration distante sécurisée via chiffrement.' },
          { type: 'code', content: '# Installer le serveur SSH\napt install openssh-server\nsystemctl enable --now ssh\n\n# Se connecter depuis un client\nssh anthony@192.168.1.10\nssh -p 2222 anthony@192.168.1.10  # port personnalisé\n\n# Configurer SSH (/etc/ssh/sshd_config)\nPort 22\nPermitRootLogin no          # Désactiver connexion root directe\nPasswordAuthentication yes\nMaxAuthTries 3\n\n# Redémarrer après modification\nsystemctl restart ssh' },
          { type: 'warn', content: 'Toujours désactiver PermitRootLogin et changer le port par défaut en production.' },
          { type: 'h2', content: 'Apache2 — Serveur Web' },
          { type: 'code', content: 'apt install apache2\nsystemctl enable --now apache2\n\n# Tester localement\ncurl http://localhost\n\n# Fichiers de configuration\n# Site par défaut : /etc/apache2/sites-available/000-default.conf\n# Racine web : /var/www/html/\n\n# Activer/désactiver un site\na2ensite monsite.conf\na2dissite 000-default.conf\nsystemctl reload apache2\n\n# Logs Apache\ntail -f /var/log/apache2/access.log\ntail -f /var/log/apache2/error.log' },
          { type: 'h2', content: 'Samba — Partage de fichiers Windows/Linux' },
          { type: 'code', content: 'apt install samba\n\n# Configurer /etc/samba/smb.conf\n[partage]\npath = /srv/partage\nbrowseable = yes\nread only = no\nvalid users = anthony\n\n# Créer le dossier et les droits\nmkdir -p /srv/partage\nchown anthony:anthony /srv/partage\nchmod 770 /srv/partage\n\n# Créer un utilisateur Samba\nsmbpasswd -a anthony\nsystemctl restart smbd' },
          { type: 'h2', content: 'UFW — Pare-feu simplifié' },
          { type: 'code', content: '# Activer UFW\nufw enable\n\n# Autoriser SSH (AVANT d\'activer !)\nufw allow ssh\nufw allow 22/tcp\n\n# Autoriser HTTP et HTTPS\nufw allow 80/tcp\nufw allow 443/tcp\n\n# Voir les règles\nufw status verbose\n\n# Supprimer une règle\nufw delete allow 80/tcp' },
        ],
      },
      {
        id: 'securite-logs-linux',
        titre: 'Sécurité et Analyse des Logs Linux',
        sections: [
          { type: 'h2', content: 'Fichiers de logs essentiels' },
          { type: 'table', headers: ['Fichier', 'Contenu'], rows: [
            ['<code>/var/log/syslog</code>',             'Logs système généraux'],
            ['<code>/var/log/auth.log</code>',           'Authentifications et sudo'],
            ['<code>/var/log/apache2/access.log</code>', 'Requêtes HTTP reçues'],
            ['<code>/var/log/apache2/error.log</code>',  'Erreurs Apache'],
            ['<code>/var/log/dpkg.log</code>',           'Installations de paquets'],
          ]},
          { type: 'code', content: '# Rechercher les échecs de connexion SSH\ngrep "Failed password" /var/log/auth.log\n\n# Voir les connexions réussies\ngrep "Accepted" /var/log/auth.log\n\n# Analyser avec journalctl\njournalctl -u ssh --since "2024-01-01" --until "2024-12-31"\njournalctl -p err  # uniquement les erreurs' },
          { type: 'h2', content: 'Fail2ban — Protection contre les attaques brute force' },
          { type: 'code', content: 'apt install fail2ban\n\n# Configuration /etc/fail2ban/jail.local\n[sshd]\nenabled = true\nmaxretry = 3\nbantime = 3600\nfindtime = 600\n\nsystemctl enable --now fail2ban\n\n# Voir les IPs bannies\nfail2ban-client status sshd' },
          { type: 'h2', content: 'Sudo et élévation de privilèges' },
          { type: 'code', content: '# Éditer sudoers (toujours via visudo !)\nvisudo\n\n# Autoriser un utilisateur à tout faire\nanthony ALL=(ALL:ALL) ALL\n\n# Autoriser sans mot de passe (déconseillé)\nanthony ALL=(ALL) NOPASSWD: ALL\n\n# Autoriser seulement certaines commandes\nanthony ALL=(ALL) /bin/systemctl, /usr/bin/apt' },
        ],
      },
    ],
    flashcards: [
      { id: 'lsf1',  recto: 'Commande pour voir les logs en temps réel ?',        verso: 'journalctl -f  ou  tail -f /var/log/syslog' },
      { id: 'lsf2',  recto: 'Comment ajouter un utilisateur au groupe sudo ?',    verso: 'usermod -aG sudo username' },
      { id: 'lsf3',  recto: 'Commande pour activer un service au démarrage ?',    verso: 'systemctl enable nom_service' },
      { id: 'lsf4',  recto: 'Où se trouve la config SSH serveur ?',               verso: '/etc/ssh/sshd_config' },
      { id: 'lsf5',  recto: 'Commande pour voir l\'espace disque ?',              verso: 'df -h (disques) et du -sh dossier (taille d\'un dossier)' },
      { id: 'lsf6',  recto: 'Qu\'est-ce que Fail2ban ?',                          verso: 'Outil qui bannit automatiquement les IPs après X tentatives de connexion échouées' },
      { id: 'lsf7',  recto: 'Port par défaut SSH ?',                              verso: 'Port 22 TCP' },
      { id: 'lsf8',  recto: 'Commande pour éditer la crontab ?',                  verso: 'crontab -e (utilisateur courant) ou crontab -e -u username (autre user)' },
      { id: 'lsf9',  recto: 'Format d\'une ligne crontab ?',                      verso: 'minute heure jour mois jour_semaine commande (ex: 0 2 * * * /script.sh)' },
      { id: 'lsf10', recto: 'Commande pour autoriser SSH dans UFW ?',             verso: 'ufw allow ssh  ou  ufw allow 22/tcp' },
      { id: 'lsf11', recto: 'Où se trouvent les sites Apache ?',                  verso: '/etc/apache2/sites-available/ (disponibles) et sites-enabled/ (actifs)' },
      { id: 'lsf12', recto: 'Commande pour créer un utilisateur Samba ?',         verso: 'smbpasswd -a username' },
      { id: 'lsf13', recto: 'Logs d\'authentification Linux ?',                   verso: '/var/log/auth.log' },
      { id: 'lsf14', recto: 'Comment voir la RAM utilisée ?',                     verso: 'free -h' },
      { id: 'lsf15', recto: 'Commande pour voir tous les services actifs ?',      verso: 'systemctl list-units --type=service --state=active' },
    ],
    qcm: [
      {
        id: 'lsq1',
        question: 'Quel fichier contient la configuration du serveur SSH ?',
        options: [
          { text: '/etc/ssh/ssh_config',  correct: false },
          { text: '/etc/ssh/sshd_config', correct: true  },
          { text: '/etc/sshd/config',     correct: false },
          { text: '/usr/ssh/config',      correct: false },
        ],
        explication: 'sshd_config configure le serveur SSH (sshd). ssh_config configure le client SSH.',
      },
      {
        id: 'lsq2',
        question: 'Quelle commande active UFW ?',
        options: [
          { text: 'ufw start',           correct: false },
          { text: 'ufw enable',          correct: true  },
          { text: 'systemctl start ufw', correct: false },
          { text: 'iptables -A UFW',     correct: false },
        ],
        explication: 'ufw enable active le pare-feu UFW et le configure pour démarrer au boot.',
      },
      {
        id: 'lsq3',
        question: 'Où se trouvent les fichiers web par défaut d\'Apache2 ?',
        options: [
          { text: '/etc/apache2/',       correct: false },
          { text: '/usr/share/apache2/', correct: false },
          { text: '/var/www/html/',      correct: true  },
          { text: '/srv/www/',           correct: false },
        ],
        explication: '/var/www/html/ est la racine web par défaut d\'Apache2 sur Debian/Ubuntu.',
      },
      {
        id: 'lsq4',
        question: 'Quelle commande liste les tâches cron de l\'utilisateur courant ?',
        options: [
          { text: 'cron -l',               correct: false },
          { text: 'crontab -l',            correct: true  },
          { text: 'cat /etc/crontab',      correct: false },
          { text: 'systemctl status cron', correct: false },
        ],
        explication: 'crontab -l liste les tâches planifiées de l\'utilisateur courant. /etc/crontab est la crontab système.',
      },
      {
        id: 'lsq5',
        question: 'Quel fichier de log contient les tentatives de connexion SSH échouées ?',
        options: [
          { text: '/var/log/syslog',   correct: false },
          { text: '/var/log/messages', correct: false },
          { text: '/var/log/auth.log', correct: true  },
          { text: '/var/log/ssh.log',  correct: false },
        ],
        explication: '/var/log/auth.log contient toutes les authentifications (SSH, sudo, su) réussies et échouées.',
      },
      {
        id: 'lsq6',
        question: 'Comment redémarrer Apache après modification de sa config ?',
        options: [
          { text: 'apache2 restart',           correct: false },
          { text: 'systemctl restart apache2', correct: true  },
          { text: 'service apache reload',     correct: false },
          { text: 'apachectl -k reboot',       correct: false },
        ],
        explication: 'systemctl restart apache2 arrête et redémarre Apache. systemctl reload recharge la config sans coupure.',
      },
      {
        id: 'lsq7',
        question: 'Quelle commande Samba crée un utilisateur Samba ?',
        options: [
          { text: 'adduser samba username',      correct: false },
          { text: 'smbpasswd -a username',       correct: true  },
          { text: 'net user username /add',      correct: false },
          { text: 'samba-user -create username', correct: false },
        ],
        explication: 'smbpasswd -a crée un compte Samba pour l\'utilisateur. Le compte Linux doit exister au préalable.',
      },
      {
        id: 'lsq8',
        question: 'Quelle option de sshd_config désactive la connexion root directe ?',
        options: [
          { text: 'RootLogin no',       correct: false },
          { text: 'PermitRoot false',   correct: false },
          { text: 'PermitRootLogin no', correct: true  },
          { text: 'DenyRoot yes',       correct: false },
        ],
        explication: 'PermitRootLogin no dans sshd_config empêche la connexion SSH directe en root. Bonne pratique de sécurité.',
      },
    ],
  },
  {
    id: 'windows',
    label: 'Windows',
    icon: '🪟',
    color: '#0ea5e9',
    desc: 'Gestion des disques, SAM, droits NTFS, pare-feu, BitLocker...',
    topics: ['Diskpart', 'SAM', 'NTFS', 'icacls', 'BitLocker', 'Pare-feu'],
    cours: [
      {
        id: 'cours_windows_objectifs',
        titre: 'Administration Windows : Disques, SAM, NTFS et Sécurisation',
        sections: [
          { type: 'html-file', src: 'modules/windows/cours_windows_objectifs.html' },
        ],
      },
      {
        id: 'admin-windows-test',
        titre: 'Administration Windows — CMD & PowerShell',
        badge: 'test',
        sections: [
          { type: 'h2', content: '1. Gestion des Utilisateurs et Groupes (CMD - Net)' },
          { type: 'warn', content: 'L\'invite de commande doit être lancée en mode Administrateur.' },
          { type: 'ul', items: [
            '<code>net user Anthony P@ssword123 /add</code> : Crée un compte utilisateur.',
            '<code>net localgroup Support /add</code> : Crée un groupe local nommé "Support".',
            '<code>net localgroup Support Anthony /add</code> : Ajoute l\'utilisateur au groupe.',
            '<code>net user Anthony</code> : Affiche les informations complètes du compte.',
          ]},
          { type: 'h2', content: '2. Gestion des Disques (Diskpart)' },
          { type: 'warn', content: '<strong>ATTENTION :</strong> La commande <code>clean</code> supprime toutes les données du disque sélectionné.' },
          { type: 'code', content: 'diskpart               # Lance l\'outil\nlist disk              # Liste les disques physiques\nselect disk 0          # Sélectionne le disque 0\nclean                  # Efface toute la structure\ncreate partition primary size=50000  # Partition de 50Go\nformat fs=ntfs quick   # Formatage rapide\nassign letter=E        # Monte le disque en E:' },
          { type: 'h2', content: '3. Administration Domaine (Active Directory)' },
          { type: 'ul', items: [
            '<code>wmic computersystem get domain</code> : Vérifie à quel domaine appartient la machine.',
            '<code>Add-Computer -DomainName "carrefour.local" -Credential (Get-Credential)</code> : Joint la machine au domaine (PowerShell).',
          ]},
          { type: 'h2', content: '4. PowerShell — Cmdlets essentielles' },
          { type: 'info', content: 'Syntaxe basée sur <strong>Verbe-Nom</strong>. Les résultats sont des objets manipulables.' },
          { type: 'ul', items: [
            '<code>Get-Process</code> : Liste les processus.',
            '<code>Stop-Process -Name "chrome" -Force</code> : Tue un processus par son nom.',
            '<code>Get-Service</code> : Liste les services Windows.',
            '<code>Restart-Service -Name "wuauserv"</code> : Redémarre Windows Update.',
            '<strong>Pipe :</strong> <code>Get-Process | Where-Object {$_.CPU -gt 100}</code> : Filtre les processus gourmands en CPU.',
          ]},
          { type: 'h2', content: '5. Diagnostic Réseau' },
          { type: 'table', headers: ['Problème', 'Commande'], rows: [
            ['Info IP/DNS/DHCP', '<code>ipconfig /all</code>'],
            ['Vérifier connectivité', '<code>ping 8.8.8.8</code>'],
            ['Vérifier résolution DNS', '<code>nslookup google.com</code>'],
            ['Vider cache DNS', '<code>ipconfig /flushdns</code>'],
            ['Chemin réseau', '<code>route print</code>'],
          ]},
          { type: 'h2', content: '6. Quiz rapide' },
          { type: 'ul', items: [
            'Redémarrer le service DNS ? → <code>Restart-Service Dnscache</code>',
            'Lister les disques via diskpart ? → <code>list disk</code>',
            'Tuer un processus par son nom ? → <code>taskkill /F /IM nom.exe</code>',
          ]},
        ],
      },
    ],
    flashcards: [],
    qcm: [],
    windows_cli: true,
    netrunner: true,
  },
  {
    id: 'windows-server',
    label: 'Windows Server 2025',
    icon: '🖥️',
    color: '#0ea5e9',
    desc: 'Installation, configuration, Active Directory, GPO, DNS, DHCP...',
    topics: ['Installation', 'AD DS', 'GPO', 'DNS', 'DHCP', 'IIS', 'RDS'],
    windows_cli: true,
    cours: [
      {
        id: 'install-ws2025',
        titre: 'Installation Windows Server 2025',
        sections: [
          { type: 'h2', content: 'Prérequis matériels' },
          { type: 'table', headers: ['Composant', 'Minimum', 'Recommandé'], rows: [
            ['CPU',    '2 GHz 64 bits',  '2 GHz 64 bits (multicœur)'],
            ['RAM',    '2 Go',            '16 Go'],
            ['Disque', '32 Go',           '100 Go'],
            ['Réseau', 'Carte Ethernet',  'Carte Ethernet Gigabit'],
          ]},
          { type: 'h2', content: 'Éditions disponibles' },
          { type: 'table', headers: ['Édition', 'Description'], rows: [
            ['Standard',   'Virtualisation limitée : 2 VMs incluses'],
            ['Datacenter', 'VMs illimitées — environnements cloud et datacenter'],
            ['Essentials', '25 utilisateurs max — petites structures'],
          ]},
          { type: 'h2', content: 'Processus d\'installation pas à pas' },
          { type: 'steps', items: [
            { num: '1', title: 'Démarrer depuis l\'ISO',         content: 'Sélectionner la langue, le fuseau horaire et la disposition du clavier.' },
            { num: '2', title: 'Choisir l\'édition',             content: '<strong>Standard avec interface graphique</strong> (Desktop Experience) recommandé pour débuter.' },
            { num: '3', title: 'Type d\'installation',           content: '<strong>Personnalisée</strong> — nouvelle installation propre sur le disque cible.' },
            { num: '4', title: 'Partitionnement',                content: 'Créer une partition système de <strong>100 Go minimum</strong>.' },
            { num: '5', title: 'Mot de passe Administrateur',    content: 'Minimum 12 caractères — majuscule + chiffre + symbole obligatoire.' },
            { num: '6', title: 'Configuration post-installation', content: 'Renommer le serveur, configurer l\'IP fixe, activer Windows Update.' },
          ]},
          { type: 'h2', content: 'Configuration IP fixe (PowerShell)' },
          { type: 'code', content: 'New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress 192.168.1.10 -PrefixLength 24 -DefaultGateway 192.168.1.1\nSet-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses 192.168.1.10' },
          { type: 'h2', content: 'Renommer le serveur' },
          { type: 'code', content: 'Rename-Computer -NewName "SRV-TSSR-01" -Restart' },
          { type: 'warn', content: 'Toujours configurer une IP fixe avant de promouvoir en contrôleur de domaine.' },
          { type: 'h2', content: 'Gestionnaire de serveur (Server Manager)' },
          { type: 'p', content: 'Interface centrale de Windows Server. Permet d\'ajouter des rôles et fonctionnalités, surveiller les événements et gérer les services.' },
          { type: 'ul', items: [
            'Tableau de bord',
            'Serveur local',
            'Tous les serveurs',
            'Rôles installés',
          ]},
        ],
      },
      {
        id: 'active-directory',
        titre: 'Active Directory — Installation et Configuration',
        sections: [
          { type: 'h2', content: 'Qu\'est-ce qu\'Active Directory ?' },
          { type: 'p', content: 'Service d\'annuaire Microsoft qui centralise l\'authentification et la gestion des ressources réseau. Basé sur les protocoles LDAP et Kerberos.' },
          { type: 'table', headers: ['Objet', 'Description', 'Exemple'], rows: [
            ['Domaine',               'Unité administrative principale',         'tssr.local'],
            ['Forêt',                 'Ensemble de domaines liés',               'tssr.local + filiale.tssr.local'],
            ['OU (Unité d\'Org.)',    'Conteneur pour organiser les objets',     'OU=Informatique,DC=tssr,DC=local'],
            ['Utilisateur',           'Compte d\'accès',                         'anthony.agnolon@tssr.local'],
            ['Groupe',                'Collection d\'utilisateurs',               'GRP-Admins-IT'],
            ['GPO',                   'Stratégie de groupe',                      'Fond d\'écran imposé'],
          ]},
          { type: 'h2', content: 'Installer le rôle AD DS' },
          { type: 'steps', items: [
            { num: '1', title: 'Via Server Manager',                   content: 'Gérer → Ajouter des rôles → Active Directory Domain Services → Suivant jusqu\'à Installation.' },
            { num: '2', title: 'Via PowerShell',                       code: 'Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools' },
            { num: '3', title: 'Promouvoir en contrôleur de domaine',  content: 'Cliquer sur le drapeau jaune dans Server Manager → Promouvoir ce serveur.' },
            { num: '4', title: 'Nouvelle forêt',                       content: 'Nom de domaine racine : <code>tssr.local</code>' },
            { num: '5', title: 'Niveau fonctionnel',                   content: 'Windows Server 2016 minimum recommandé.' },
            { num: '6', title: 'Mot de passe DSRM',                   content: 'Mode restauration des services d\'annuaire — à conserver précieusement.' },
            { num: '7', title: 'Redémarrage automatique',              content: 'Le serveur redémarre et devient contrôleur de domaine.' },
          ]},
          { type: 'h2', content: 'Gestion des utilisateurs (PowerShell)' },
          { type: 'code', content: '# Créer un utilisateur\nNew-ADUser -Name "Jean Dupont" -GivenName "Jean" -Surname "Dupont" `\n  -SamAccountName "j.dupont" -UserPrincipalName "j.dupont@tssr.local" `\n  -Path "OU=Utilisateurs,DC=tssr,DC=local" `\n  -AccountPassword (ConvertTo-SecureString "P@ssword123" -AsPlainText -Force) `\n  -Enabled $true\n\n# Lister tous les utilisateurs\nGet-ADUser -Filter * | Select-Object Name, SamAccountName, Enabled\n\n# Désactiver un compte\nDisable-ADAccount -Identity "j.dupont"\n\n# Réinitialiser un mot de passe\nSet-ADAccountPassword -Identity "j.dupont" -Reset `\n  -NewPassword (ConvertTo-SecureString "NewP@ss123" -AsPlainText -Force)' },
          { type: 'h2', content: 'Gestion des groupes' },
          { type: 'code', content: '# Créer un groupe\nNew-ADGroup -Name "GRP-Informatique" -GroupScope Global -GroupCategory Security `\n  -Path "OU=Groupes,DC=tssr,DC=local"\n\n# Ajouter un membre\nAdd-ADGroupMember -Identity "GRP-Informatique" -Members "j.dupont"\n\n# Lister les membres\nGet-ADGroupMember -Identity "GRP-Informatique"' },
          { type: 'h2', content: 'Gestion des Unités d\'Organisation' },
          { type: 'code', content: '# Créer une OU\nNew-ADOrganizationalUnit -Name "Informatique" -Path "DC=tssr,DC=local"\n\n# Lister les OUs\nGet-ADOrganizationalUnit -Filter * | Select-Object Name, DistinguishedName' },
          { type: 'h2', content: 'GPO — Stratégies de Groupe' },
          { type: 'p', content: 'Les GPO permettent d\'imposer des paramètres sur les utilisateurs et ordinateurs du domaine.' },
          { type: 'steps', items: [
            { num: '1', title: 'Ouvrir GPMC',            content: '<code>gpmc.msc</code> dans Exécuter (Win+R).' },
            { num: '2', title: 'Créer une GPO',           content: 'Clic droit sur l\'OU cible → Créer un objet GPO dans ce domaine.' },
            { num: '3', title: 'Modifier la GPO',         content: 'Clic droit → Modifier → Configuration utilisateur ou Configuration ordinateur.' },
            { num: '4', title: 'Exemples utiles',         content: 'Fond d\'écran imposé, désactiver les ports USB, mapper un lecteur réseau.' },
            { num: '5', title: 'Forcer l\'application',   code: 'gpupdate /force' },
          ]},
          { type: 'code', content: '# Voir les GPO appliquées sur un poste client\ngpresult /R\ngpresult /H rapport.html' },
        ],
      },
      {
        id: 'dns-dhcp',
        titre: 'DNS &amp; DHCP sur Windows Server',
        sections: [
          { type: 'h2', content: 'DNS — Domain Name System' },
          { type: 'p', content: 'Traduit les noms de domaine en adresses IP. Essentiel au fonctionnement d\'Active Directory.' },
          { type: 'table', headers: ['Type', 'Rôle', 'Exemple'], rows: [
            ['A',     'Nom → IPv4',               'srv01.tssr.local → 192.168.1.10'],
            ['AAAA',  'Nom → IPv6',               'srv01.tssr.local → ::1'],
            ['PTR',   'IPv4 → Nom (DNS inversé)', '192.168.1.10 → srv01.tssr.local'],
            ['MX',    'Serveur mail',              'tssr.local → mail.tssr.local'],
            ['CNAME', 'Alias',                     'www.tssr.local → srv-web.tssr.local'],
          ]},
          { type: 'code', content: '# Installer le rôle DNS\nInstall-WindowsFeature -Name DNS -IncludeManagementTools\n\n# Créer un enregistrement A\nAdd-DnsServerResourceRecordA -ZoneName "tssr.local" -Name "srv-web" -IPv4Address "192.168.1.20"\n\n# Vérifier la résolution\nResolve-DnsName srv-web.tssr.local\n\n# Vider le cache DNS\nClear-DnsServerCache' },
          { type: 'h2', content: 'DHCP — Dynamic Host Configuration Protocol' },
          { type: 'p', content: 'Attribue automatiquement les paramètres réseau aux clients : adresse IP, masque, passerelle, serveur DNS.' },
          { type: 'steps', items: [
            { num: '1', title: 'Installer le rôle DHCP',       code: 'Install-WindowsFeature -Name DHCP -IncludeManagementTools' },
            { num: '2', title: 'Autoriser le serveur dans AD',  code: 'Add-DhcpServerInDC -DnsName "srv01.tssr.local"' },
            { num: '3', title: 'Créer une étendue',             content: 'Définir la plage d\'adresses IP à distribuer aux clients.' },
            { num: '4', title: 'Configurer les options',        content: 'Passerelle (option 3), DNS (option 6), Domaine (option 15).' },
            { num: '5', title: 'Activer l\'étendue',            content: 'Mettre l\'étendue en état Actif pour commencer la distribution des baux.' },
          ]},
          { type: 'code', content: '# Créer une étendue DHCP\nAdd-DhcpServerv4Scope -Name "LAN-Principal" `\n  -StartRange 192.168.1.100 -EndRange 192.168.1.200 `\n  -SubnetMask 255.255.255.0 -State Active\n\n# Configurer les options\nSet-DhcpServerv4OptionValue -ScopeId 192.168.1.0 `\n  -Router 192.168.1.1 `\n  -DnsServer 192.168.1.10 `\n  -DnsDomain "tssr.local"\n\n# Voir les baux actifs\nGet-DhcpServerv4Lease -ScopeId 192.168.1.0' },
        ],
      },
    ],
    flashcards: [
      { id: 'f1',  recto: 'Quel port utilise LDAP ?',                              verso: 'Port 389 (LDAP) et 636 (LDAPS chiffré)' },
      { id: 'f2',  recto: 'Quel protocole utilise AD pour l\'authentification ?',  verso: 'Kerberos (port 88) — tickets d\'authentification chiffrés' },
      { id: 'f3',  recto: 'Commande pour forcer l\'application des GPO ?',          verso: 'gpupdate /force' },
      { id: 'f4',  recto: 'Qu\'est-ce qu\'une OU ?',                               verso: 'Unité d\'Organisation — conteneur AD pour organiser utilisateurs, groupes et ordinateurs' },
      { id: 'f5',  recto: 'Différence groupe Global vs Universel ?',               verso: 'Global : membres du même domaine. Universel : membres de toute la forêt.' },
      { id: 'f6',  recto: 'Commande PowerShell pour créer un utilisateur AD ?',    verso: 'New-ADUser -Name "Nom" -SamAccountName "login" -Enabled $true' },
      { id: 'f7',  recto: 'Qu\'est-ce que le DSRM ?',                              verso: 'Directory Services Restore Mode — mode de récupération du contrôleur de domaine' },
      { id: 'f8',  recto: 'Port utilisé par DNS ?',                                verso: 'Port 53 (UDP pour les requêtes, TCP pour les transferts de zone)' },
      { id: 'f9',  recto: 'Qu\'est-ce qu\'un enregistrement PTR ?',                verso: 'Enregistrement DNS inversé : IP → Nom (ex: 192.168.1.10 → srv01.tssr.local)' },
      { id: 'f10', recto: 'Port DHCP serveur et client ?',                         verso: 'Serveur : UDP 67 — Client : UDP 68' },
      { id: 'f11', recto: 'Les 4 étapes du processus DHCP ?',                      verso: 'DORA : Discover → Offer → Request → Acknowledge' },
      { id: 'f12', recto: 'Commande pour voir les GPO appliquées ?',               verso: 'gpresult /R (texte) ou gpresult /H rapport.html (HTML)' },
      { id: 'f13', recto: 'Qu\'est-ce qu\'une forêt AD ?',                         verso: 'Ensemble de domaines AD partageant un schéma commun et des relations d\'approbation' },
      { id: 'f14', recto: 'Commande pour promouvoir un serveur en DC ?',           verso: 'Install-ADDSForest (nouvelle forêt) ou Install-ADDSDomainController (domaine existant)' },
      { id: 'f15', recto: 'Quel outil graphique gère les GPO ?',                   verso: 'GPMC — Group Policy Management Console (gpmc.msc)' },
      { id: 'f16', recto: 'Commande pour joindre un PC au domaine ?',              verso: 'Add-Computer -DomainName "tssr.local" -Credential (Get-Credential) -Restart' },
      { id: 'f17', recto: 'Qu\'est-ce que le catalogue global AD ?',               verso: 'Serveur qui stocke une copie partielle de tous les objets de la forêt pour accélérer les recherches' },
      { id: 'f18', recto: 'Différence entre DNS primaire et secondaire ?',         verso: 'Primaire : zone en lecture/écriture. Secondaire : copie en lecture seule (redondance).' },
      { id: 'f19', recto: 'Commande pour lister les DCs du domaine ?',             verso: 'Get-ADDomainController -Filter *' },
      { id: 'f20', recto: 'Qu\'est-ce que Sysvol ?',                               verso: 'Dossier partagé sur tous les DCs contenant les scripts de connexion et les fichiers GPO' },
    ],
    qcm: [
      {
        id: 'q1',
        question: 'Quel est le port par défaut de LDAP ?',
        options: [
          { text: '389', correct: true  },
          { text: '443', correct: false },
          { text: '636', correct: false },
          { text: '88',  correct: false },
        ],
        explication: 'LDAP utilise le port 389. LDAPS (chiffré) utilise le port 636. Kerberos utilise le port 88.',
      },
      {
        id: 'q2',
        question: 'Quelle commande permet de forcer l\'application des GPO sur un client ?',
        options: [
          { text: 'gpedit /refresh', correct: false },
          { text: 'gpupdate /force', correct: true  },
          { text: 'gpresult /R',     correct: false },
          { text: 'gpmc /update',    correct: false },
        ],
        explication: 'gpupdate /force force la mise à jour immédiate de toutes les stratégies de groupe.',
      },
      {
        id: 'q3',
        question: 'Qu\'est-ce que DORA dans le contexte DHCP ?',
        options: [
          { text: 'Un protocole de sécurité',                             correct: false },
          { text: 'Les 4 étapes : Discover, Offer, Request, Acknowledge', correct: true  },
          { text: 'Un type de groupe AD',                                  correct: false },
          { text: 'Un rôle Windows Server',                                correct: false },
        ],
        explication: 'DORA décrit le processus d\'attribution d\'adresse IP : le client diffuse (Discover), le serveur propose (Offer), le client demande (Request), le serveur confirme (Acknowledge).',
      },
      {
        id: 'q4',
        question: 'Quelle édition de Windows Server 2025 permet des VMs illimitées ?',
        options: [
          { text: 'Standard',   correct: false },
          { text: 'Essentials', correct: false },
          { text: 'Datacenter', correct: true  },
          { text: 'Foundation', correct: false },
        ],
        explication: 'L\'édition Datacenter permet un nombre illimité de machines virtuelles. Standard en permet seulement 2.',
      },
      {
        id: 'q5',
        question: 'Quel protocole Active Directory gère l\'authentification ?',
        options: [
          { text: 'NTLM uniquement', correct: false },
          { text: 'Kerberos',        correct: true  },
          { text: 'RADIUS',          correct: false },
          { text: 'TACACS+',         correct: false },
        ],
        explication: 'Kerberos est le protocole d\'authentification principal d\'Active Directory depuis Windows 2000. Il utilise des tickets chiffrés.',
      },
      {
        id: 'q6',
        question: 'Quelle commande PowerShell crée une étendue DHCP ?',
        options: [
          { text: 'New-DhcpScope',         correct: false },
          { text: 'Add-DhcpServerv4Scope', correct: true  },
          { text: 'Create-DhcpRange',      correct: false },
          { text: 'Set-DhcpServerv4Scope', correct: false },
        ],
        explication: 'Add-DhcpServerv4Scope crée une nouvelle étendue DHCP IPv4 avec les paramètres de plage et de masque.',
      },
      {
        id: 'q7',
        question: 'Qu\'est-ce qu\'une OU dans Active Directory ?',
        options: [
          { text: 'Un type de serveur DNS',                    correct: false },
          { text: 'Un conteneur pour organiser les objets AD', correct: true  },
          { text: 'Un protocole d\'authentification',          correct: false },
          { text: 'Une stratégie de groupe',                   correct: false },
        ],
        explication: 'Une OU (Organizational Unit) est un conteneur qui permet d\'organiser les utilisateurs, groupes et ordinateurs dans AD, et d\'y appliquer des GPO ciblées.',
      },
      {
        id: 'q8',
        question: 'Sur quel port fonctionne DNS ?',
        options: [
          { text: 'Port 80',  correct: false },
          { text: 'Port 443', correct: false },
          { text: 'Port 53',  correct: true  },
          { text: 'Port 25',  correct: false },
        ],
        explication: 'DNS utilise le port 53 — UDP pour les requêtes standard, TCP pour les transferts de zone.',
      },
      {
        id: 'q9',
        question: 'Quelle commande joint un PC Windows au domaine tssr.local ?',
        options: [
          { text: 'Join-Domain -Name tssr.local',        correct: false },
          { text: 'Add-Computer -DomainName tssr.local', correct: true  },
          { text: 'Connect-Domain tssr.local',           correct: false },
          { text: 'Set-ADComputer -Domain tssr.local',   correct: false },
        ],
        explication: 'Add-Computer -DomainName "tssr.local" -Credential (Get-Credential) -Restart joint le PC au domaine et redémarre.',
      },
      {
        id: 'q10',
        question: 'Qu\'est-ce que Sysvol ?',
        options: [
          { text: 'Un service de sauvegarde AD',                              correct: false },
          { text: 'Le dossier partagé contenant les scripts et fichiers GPO', correct: true  },
          { text: 'Un protocole de réplication DNS',                          correct: false },
          { text: 'Un outil de monitoring AD',                                correct: false },
        ],
        explication: 'Sysvol est un dossier partagé répliqué sur tous les contrôleurs de domaine. Il contient les scripts de connexion et les modèles de stratégies de groupe.',
      },
    ],
  },
  {
    id: 'virtualisation',
    label: 'Virtualisation',
    icon: '📦',
    color: '#8b5cf6',
    desc: 'Concepts, VMware Workstation, Hyper-V, VirtualBox — création et gestion de VMs',
    topics: ['Hyperviseur', 'VMware', 'Hyper-V', 'VirtualBox', 'Snapshots', 'Réseaux VM'],
    windows_cli: true,
    cours: [
      {
        id: 'concepts-virtualisation',
        titre: 'Concepts de la Virtualisation',
        sections: [
          { type: 'h2', content: 'Qu\'est-ce que la virtualisation ?' },
          { type: 'p', content: 'La virtualisation permet d\'exécuter plusieurs systèmes d\'exploitation (invités) sur une seule machine physique (hôte) grâce à un logiciel appelé hyperviseur.' },
          { type: 'h2', content: 'Types d\'hyperviseurs' },
          { type: 'table', headers: ['Type', 'Description', 'Exemples'], rows: [
            ['Type 1 (bare-metal)', 'S\'installe directement sur le matériel, sans OS hôte. Plus performant.', 'VMware ESXi, Hyper-V, Proxmox VE'],
            ['Type 2 (hosted)',     'S\'installe sur un OS hôte existant. Plus simple à déployer.',           'VMware Workstation, VirtualBox, Parallels'],
          ]},
          { type: 'h2', content: 'Comparatif des solutions' },
          { type: 'table', headers: ['Solution', 'Type', 'Usage principal', 'Licence'], rows: [
            ['VMware ESXi',        'Type 1', 'Datacenter, production',         'Commerciale (Free tier limité)'],
            ['Hyper-V',            'Type 1/2', 'Windows Server, poste Windows', 'Inclus dans Windows'],
            ['VMware Workstation', 'Type 2', 'Développement, tests',           'Commerciale (gratuite pour perso)'],
            ['VirtualBox',         'Type 2', 'Formation, cross-platform',      'Open source (gratuit)'],
            ['Proxmox VE',         'Type 1', 'Homelab, production',            'Open source (gratuit)'],
          ]},
          { type: 'h2', content: 'Terminologie essentielle' },
          { type: 'table', headers: ['Terme', 'Définition'], rows: [
            ['VM (Machine Virtuelle)', 'Système invité complet émulé par l\'hyperviseur'],
            ['Snapshot',               'Sauvegarde de l\'état d\'une VM à un instant T — restauration rapide'],
            ['Template / Modèle',      'VM de référence clonée pour créer d\'autres VMs identiques'],
            ['OVA / OVF',              'Format standard d\'export/import de VMs entre hyperviseurs'],
            ['vCPU',                   'Cœur de processeur virtuel alloué à la VM'],
            ['vRAM',                   'Mémoire RAM virtuelle allouée à la VM'],
            ['Datastore',              'Espace de stockage hébergeant les fichiers de VMs (VMDK, VHDX...)'],
          ]},
          { type: 'h2', content: 'Modes réseau des VMs' },
          { type: 'table', headers: ['Mode', 'Description', 'Usage'], rows: [
            ['NAT',        'La VM partage l\'IP de l\'hôte — réseau via translation d\'adresses', 'Accès Internet simple, VM non visible du LAN'],
            ['Bridge',     'La VM obtient sa propre IP sur le réseau physique',                   'VM visible du réseau local, serveur de test'],
            ['Host-Only',  'Réseau isolé entre la VM et l\'hôte uniquement',                      'Lab isolé, pas d\'accès Internet'],
            ['Interne',    'Réseau entre VMs uniquement, hôte exclu',                             'Topologies réseau simulées'],
          ]},
        ],
      },
      {
        id: 'vmware-workstation',
        titre: 'VMware Workstation — Création et Gestion de VMs',
        sections: [
          { type: 'h2', content: 'Créer une VM sous VMware Workstation' },
          { type: 'steps', items: [
            { num: '1', title: 'Nouvelle VM',            content: 'File → New Virtual Machine → <strong>Typical</strong> (recommandé).' },
            { num: '2', title: 'Choisir l\'ISO',         content: 'Installer disc image file (iso) → sélectionner l\'ISO du système à installer.' },
            { num: '3', title: 'Type de système',        content: 'Sélectionner Linux ou Windows selon l\'OS — VMware adapte les paramètres.' },
            { num: '4', title: 'Nom et emplacement',     content: 'Définir le nom de la VM et le dossier de stockage (éviter les espaces dans le chemin).' },
            { num: '5', title: 'Taille du disque',       content: 'Minimum 20 Go. Cocher <strong>Store virtual disk as a single file</strong> pour de meilleures performances.' },
            { num: '6', title: 'Personnaliser le matériel', content: 'Customize Hardware → ajuster RAM, CPU, carte réseau avant le premier démarrage.' },
          ]},
          { type: 'h2', content: 'Snapshots — Gestion des états' },
          { type: 'p', content: 'Un snapshot capture l\'état complet d\'une VM (RAM + disque) pour permettre un retour arrière instantané.' },
          { type: 'steps', items: [
            { num: '1', title: 'Prendre un snapshot',    content: 'VM → Snapshot → Take Snapshot → nommer de façon descriptive (ex: "avant-apache").' },
            { num: '2', title: 'Restaurer',              content: 'VM → Snapshot → Snapshot Manager → sélectionner → <strong>Go To</strong>.' },
            { num: '3', title: 'Supprimer',              content: 'Snapshot Manager → sélectionner → Delete. Libère l\'espace disque du snapshot.' },
          ]},
          { type: 'warn', content: 'Les snapshots ne remplacent pas une sauvegarde. Ils consomment de l\'espace disque et dégradent les performances s\'ils s\'accumulent.' },
          { type: 'h2', content: 'Commandes CLI vmrun (VMware Workstation)' },
          { type: 'code', content: '# Prendre un snapshot\nvmrun snapshot "C:\\VMs\\debian.vmx" "avant-modif"\n\n# Restaurer un snapshot\nvmrun revertToSnapshot "C:\\VMs\\debian.vmx" "avant-modif"\n\n# Lister les snapshots\nvmrun listSnapshots "C:\\VMs\\debian.vmx"\n\n# Supprimer un snapshot\nvmrun deleteSnapshot "C:\\VMs\\debian.vmx" "avant-modif"\n\n# Démarrer / éteindre une VM\nvmrun start "C:\\VMs\\debian.vmx"\nvmrun stop "C:\\VMs\\debian.vmx" hard' },
          { type: 'h2', content: 'Export / Import OVA' },
          { type: 'p', content: 'L\'export OVA (Open Virtual Appliance) permet de déplacer une VM entre hyperviseurs (VMware ↔ VirtualBox ↔ Hyper-V).' },
          { type: 'steps', items: [
            { num: '1', title: 'Éteindre la VM',         content: 'La VM doit être éteinte pour un export propre.' },
            { num: '2', title: 'Exporter',               content: 'File → Export to OVF → choisir le format <strong>.ova</strong> (fichier unique).' },
            { num: '3', title: 'Importer',               content: 'File → Open → sélectionner le fichier .ova → ajuster les paramètres si besoin.' },
          ]},
        ],
      },
      {
        id: 'hyperv-powershell',
        titre: 'Hyper-V — Administration via PowerShell',
        sections: [
          { type: 'h2', content: 'Activer Hyper-V' },
          { type: 'code', content: '# Sur Windows 10/11 Pro ou Windows Server (en admin)\nEnable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All\n\n# Vérifier l\'installation\nGet-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V' },
          { type: 'info', content: '<strong>Prérequis :</strong> processeur 64 bits avec virtualisation matérielle (Intel VT-x ou AMD-V) activée dans le BIOS/UEFI.' },
          { type: 'h2', content: 'Types de commutateurs virtuels Hyper-V' },
          { type: 'table', headers: ['Type', 'Description', 'Usage'], rows: [
            ['Externe', 'Connecté à la carte réseau physique — accès réseau complet',    'VM visible du LAN, accès Internet'],
            ['Interne', 'VM ↔ hôte, isolé du réseau physique externe',                   'Lab isolé avec accès à l\'hôte'],
            ['Privé',   'VM ↔ VM uniquement, l\'hôte est exclu',                          'Topologies réseau purement virtuelles'],
          ]},
          { type: 'code', content: '# Lister les commutateurs existants\nGet-VMSwitch\n\n# Créer un commutateur externe\nNew-VMSwitch -Name "vSwitch-LAN" -NetAdapterName "Ethernet" -AllowManagementOS $true\n\n# Créer un commutateur interne\nNew-VMSwitch -Name "vSwitch-Interne" -SwitchType Internal' },
          { type: 'h2', content: 'Gestion des VMs via PowerShell' },
          { type: 'code', content: '# Créer une VM\nNew-VM -Name "VM-Debian" -MemoryStartupBytes 2GB `\n  -NewVHDPath "C:\\VMs\\debian.vhdx" -NewVHDSizeBytes 50GB `\n  -Generation 2\n\n# Lister toutes les VMs\nGet-VM\n\n# Démarrer / Arrêter\nStart-VM -Name "VM-Debian"\nStop-VM -Name "VM-Debian" -Force\n\n# Modifier la RAM\nSet-VMMemory -VMName "VM-Debian" -StartupBytes 4GB\n\n# Ajouter une carte réseau\nAdd-VMNetworkAdapter -VMName "VM-Debian" -SwitchName "vSwitch-LAN"' },
          { type: 'h2', content: 'Checkpoints (Snapshots Hyper-V)' },
          { type: 'code', content: '# Créer un checkpoint\nCheckpoint-VM -Name "VM-Debian" -SnapshotName "avant-config"\n\n# Lister les checkpoints\nGet-VMCheckpoint -VMName "VM-Debian"\n\n# Restaurer un checkpoint\nRestore-VMCheckpoint -Name "avant-config" -VMName "VM-Debian" -Confirm:$false\n\n# Supprimer un checkpoint\nRemove-VMCheckpoint -VMName "VM-Debian" -Name "avant-config"' },
          { type: 'h2', content: 'Informations et diagnostic' },
          { type: 'code', content: '# Détails complets d\'une VM\nGet-VM -Name "VM-Debian" | Select-Object *\n\n# Utilisation des ressources\nMeasure-VM -Name "VM-Debian"\n\n# Adaptateurs réseau d\'une VM\nGet-VMNetworkAdapter -VMName "VM-Debian"\n\n# Disques virtuels\nGet-VMHardDiskDrive -VMName "VM-Debian"' },
        ],
      },
    ],
    flashcards: [
      { id: 'vf1',  recto: 'Différence hyperviseur type 1 vs type 2 ?',           verso: 'Type 1 : bare-metal, sur le hardware (ESXi, Hyper-V). Type 2 : sur un OS hôte (VirtualBox, VMware Workstation).' },
      { id: 'vf2',  recto: 'Quel mode réseau VMware donne une IP du réseau local ?', verso: 'Bridge — la VM obtient sa propre IP sur le réseau physique.' },
      { id: 'vf3',  recto: 'Qu\'est-ce qu\'un snapshot ?',                        verso: 'Capture de l\'état complet d\'une VM (RAM + disque) permettant un retour arrière instantané.' },
      { id: 'vf4',  recto: 'Commande PowerShell pour créer une VM Hyper-V ?',     verso: 'New-VM -Name "NomVM" -MemoryStartupBytes 2GB -NewVHDPath "chemin.vhdx" -NewVHDSizeBytes 50GB' },
      { id: 'vf5',  recto: 'Format standard d\'export/import de VMs ?',           verso: 'OVA (fichier unique) ou OVF (dossier) — Open Virtualization Format.' },
      { id: 'vf6',  recto: 'Qu\'est-ce que NAT dans VMware ?',                    verso: 'La VM partage l\'IP de l\'hôte via translation d\'adresses. Accès Internet mais non visible du LAN.' },
      { id: 'vf7',  recto: 'Commande pour lister les VMs Hyper-V ?',              verso: 'Get-VM' },
      { id: 'vf8',  recto: 'Les 3 types de commutateurs Hyper-V ?',               verso: 'Externe (LAN physique), Interne (VM↔hôte), Privé (VM↔VM uniquement).' },
      { id: 'vf9',  recto: 'Qu\'est-ce qu\'un datastore ?',                       verso: 'Espace de stockage hébergeant les fichiers de VMs (VMDK pour VMware, VHDX pour Hyper-V).' },
      { id: 'vf10', recto: 'Commande PowerShell pour créer un snapshot Hyper-V ?', verso: 'Checkpoint-VM -Name "NomVM" -SnapshotName "nom-du-snapshot"' },
      { id: 'vf11', recto: 'Qu\'est-ce que VMware ESXi ?',                        verso: 'Hyperviseur de type 1 (bare-metal) de VMware, dédié aux environnements de production.' },
      { id: 'vf12', recto: 'Différence OVA vs OVF ?',                             verso: 'OVA = fichier unique (.ova, archive tar). OVF = dossier avec plusieurs fichiers séparés.' },
      { id: 'vf13', recto: 'Commande PowerShell pour activer Hyper-V ?',          verso: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All' },
      { id: 'vf14', recto: 'Commande pour restaurer un checkpoint Hyper-V ?',     verso: 'Restore-VMCheckpoint -Name "nom" -VMName "NomVM" -Confirm:$false' },
      { id: 'vf15', recto: 'Qu\'est-ce qu\'un template de VM ?',                  verso: 'VM de référence désactivée, clonée pour créer rapidement des VMs identiques et préconfigurées.' },
    ],
    qcm: [
      {
        id: 'vq1',
        question: 'Quel hyperviseur est de type 1 (bare-metal) ?',
        options: [
          { text: 'VMware Workstation', correct: false },
          { text: 'VirtualBox',         correct: false },
          { text: 'VMware ESXi',        correct: true  },
          { text: 'Parallels Desktop',  correct: false },
        ],
        explication: 'VMware ESXi est un hyperviseur de type 1 qui s\'installe directement sur le hardware. Workstation et VirtualBox sont de type 2 (sur un OS hôte).',
      },
      {
        id: 'vq2',
        question: 'Quel mode réseau VMware permet à la VM d\'avoir sa propre IP visible sur le réseau local ?',
        options: [
          { text: 'NAT',       correct: false },
          { text: 'Bridge',    correct: true  },
          { text: 'Host-Only', correct: false },
          { text: 'Interne',   correct: false },
        ],
        explication: 'Le mode Bridge connecte la VM directement au réseau physique. La VM obtient une IP du même réseau que l\'hôte et est visible de tous les équipements.',
      },
      {
        id: 'vq3',
        question: 'Quelle commande PowerShell liste les VMs Hyper-V ?',
        options: [
          { text: 'List-VM',        correct: false },
          { text: 'Get-VM',         correct: true  },
          { text: 'Show-HyperV',    correct: false },
          { text: 'Get-HyperV -VM', correct: false },
        ],
        explication: 'Get-VM liste toutes les VMs avec leur état (Running/Off). Get-VM -Name "NomVM" pour une VM spécifique.',
      },
      {
        id: 'vq4',
        question: 'Qu\'est-ce qu\'un snapshot (ou checkpoint Hyper-V) ?',
        options: [
          { text: 'Une sauvegarde complète de la VM sur disque externe', correct: false },
          { text: 'Une capture de l\'état de la VM permettant un retour arrière', correct: true },
          { text: 'Un clone complet de la VM',                           correct: false },
          { text: 'Un export au format OVA',                             correct: false },
        ],
        explication: 'Un snapshot capture l\'état (RAM + disque) à un instant T. Il permet de revenir à cet état rapidement. Ce n\'est pas une sauvegarde complète.',
      },
      {
        id: 'vq5',
        question: 'Quel format permet d\'importer une VM dans VMware ET dans VirtualBox ?',
        options: [
          { text: '.vmdk', correct: false },
          { text: '.vhdx', correct: false },
          { text: '.ova',  correct: true  },
          { text: '.vmx',  correct: false },
        ],
        explication: 'OVA (Open Virtualization Appliance) est un format standard ouvert pris en charge par VMware, VirtualBox et d\'autres hyperviseurs.',
      },
      {
        id: 'vq6',
        question: 'Quel type de commutateur Hyper-V permet uniquement aux VMs de communiquer entre elles (hôte exclu) ?',
        options: [
          { text: 'Externe', correct: false },
          { text: 'Interne', correct: false },
          { text: 'Privé',   correct: true  },
          { text: 'NAT',     correct: false },
        ],
        explication: 'Le commutateur Privé isole complètement les VMs du réseau externe et de l\'hôte. Idéal pour simuler des topologies réseau sans risque.',
      },
      {
        id: 'vq7',
        question: 'Quelle commande PowerShell crée un checkpoint (snapshot) Hyper-V ?',
        options: [
          { text: 'New-VMSnapshot',   correct: false },
          { text: 'Save-VM',          correct: false },
          { text: 'Checkpoint-VM',    correct: true  },
          { text: 'Backup-VMState',   correct: false },
        ],
        explication: 'Checkpoint-VM -Name "NomVM" -SnapshotName "nom" crée un checkpoint. Restore-VMCheckpoint pour restaurer.',
      },
      {
        id: 'vq8',
        question: 'En mode Host-Only (VMware), la VM peut-elle accéder à Internet ?',
        options: [
          { text: 'Oui, via l\'IP de l\'hôte',       correct: false },
          { text: 'Oui, avec sa propre IP',           correct: false },
          { text: 'Non, le réseau est isolé',         correct: true  },
          { text: 'Oui, via un pont réseau',          correct: false },
        ],
        explication: 'Host-Only crée un réseau isolé entre la VM et l\'hôte uniquement. Pas d\'accès Internet ni au réseau physique. Idéal pour les labs sécurisés.',
      },
    ],
  },
  {
    id: 'securite',
    label: 'Sécurité',
    icon: '🔐',
    color: '#ef4444',
    desc: 'PKI, certificats SSL/TLS, pare-feu, VPN, VLAN, CIA Triad...',
    topics: ['PKI', 'SSL/TLS', 'Pare-feu', 'iptables', 'VPN', 'VLAN'],
    linux_cli: true,
    windows_cli: true,
    cours: [
      {
        id: 'pki-certificats',
        titre: 'PKI et Certificats SSL/TLS',
        sections: [
          { type: 'h2', content: 'Qu\'est-ce que la PKI ?' },
          { type: 'p', content: 'Infrastructure à Clés Publiques (Public Key Infrastructure) — système de gestion des certificats numériques permettant d\'authentifier des entités et de chiffrer les échanges.' },
          { type: 'table', headers: ['Composant', 'Rôle'], rows: [
            ['CA (Certificate Authority)',  'Autorité de confiance qui signe et délivre les certificats'],
            ['Certificat X.509',            'Document numérique : clé publique + identité + signature de la CA'],
            ['Clé privée',                  'Secret conservé par le titulaire — ne jamais partager ni transmettre'],
            ['CSR',                         'Certificate Signing Request — demande de certificat envoyée à la CA'],
            ['CRL / OCSP',                  'Liste de révocation / protocole en ligne pour vérifier la validité'],
          ]},
          { type: 'h2', content: 'Chiffrement symétrique vs asymétrique' },
          { type: 'table', headers: ['Type', 'Clés', 'Vitesse', 'Usage typique'], rows: [
            ['Symétrique',   '1 clé partagée entre les deux parties',    'Rapide',  'Chiffrement de données (AES-256)'],
            ['Asymétrique',  'Paire clé publique / clé privée',          'Lent',    'SSL/TLS, SSH, signatures numériques'],
          ]},
          { type: 'h2', content: 'Fonctionnement de TLS (handshake)' },
          { type: 'steps', items: [
            { num: '1', title: 'ClientHello',       content: 'Le client envoie les versions TLS et suites cryptographiques supportées.' },
            { num: '2', title: 'ServerHello',        content: 'Le serveur répond avec son certificat et la suite choisie.' },
            { num: '3', title: 'Vérification',       content: 'Le client vérifie le certificat : validité, CA de confiance, hostname.' },
            { num: '4', title: 'Échange de clé',     content: 'Génération d\'une clé de session partagée via ECDHE (sans transmettre la clé).' },
            { num: '5', title: 'Chiffrement actif',  content: 'La communication est chiffrée avec la clé de session symétrique (AES).' },
          ]},
          { type: 'h2', content: 'Commandes OpenSSL essentielles' },
          { type: 'code', content: '# Générer une clé privée RSA 2048 bits\nopenssl genrsa -out privkey.pem 2048\n\n# Créer un CSR (Certificate Signing Request)\nopenssl req -new -key privkey.pem -out request.csr\n\n# Certificat auto-signé (valable 10 ans)\nopenssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 3650 -nodes\n\n# Vérifier un certificat\nopenssl x509 -in cert.pem -text -noout\n\n# Tester une connexion TLS\nopenssl s_client -connect exemple.com:443\n\n# Vérifier la date d\'expiration\nopenssl x509 -in cert.pem -noout -dates' },
          { type: 'warn', content: 'Ne jamais stocker la clé privée sur un serveur web accessible. Restreindre les droits : chmod 600 privkey.pem.' },
        ],
      },
      {
        id: 'pare-feu-filtrage',
        titre: 'Pare-feu et Filtrage Réseau',
        sections: [
          { type: 'h2', content: 'Types de filtrage réseau' },
          { type: 'table', headers: ['Type', 'Description', 'Exemple'], rows: [
            ['Stateless (sans état)', 'Filtre paquet par paquet sans contexte de connexion',               'ACL Cisco, iptables simple'],
            ['Stateful (avec état)',  'Suit les connexions — accepte les paquets liés aux sessions établies', 'iptables -m state, Windows Firewall'],
            ['Applicatif (L7)',       'Analyse le contenu applicatif (HTTP, DNS, SMTP)',                   'WAF, proxy Squid, Palo Alto'],
          ]},
          { type: 'h2', content: 'iptables (Linux)' },
          { type: 'code', content: '# Afficher les règles avec compteurs\niptables -L -v -n\n\n# Politique par défaut : tout bloquer en entrée\niptables -P INPUT DROP\niptables -P FORWARD DROP\niptables -P OUTPUT ACCEPT\n\n# Autoriser SSH (port 22)\niptables -A INPUT -p tcp --dport 22 -j ACCEPT\n\n# Autoriser HTTP et HTTPS\niptables -A INPUT -p tcp -m multiport --dports 80,443 -j ACCEPT\n\n# Autoriser le trafic des connexions établies\niptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT\n\n# Autoriser le loopback\niptables -A INPUT -i lo -j ACCEPT\n\n# Bloquer une IP spécifique\niptables -A INPUT -s 192.168.1.100 -j DROP\n\n# Sauvegarder les règles\niptables-save > /etc/iptables/rules.v4' },
          { type: 'h2', content: 'Windows Firewall (PowerShell)' },
          { type: 'code', content: '# Voir les profils (Domain, Private, Public)\nGet-NetFirewallProfile\n\n# Lister les règles actives\nGet-NetFirewallRule | Where-Object {$_.Enabled -eq "True"} | Select-Object DisplayName, Direction, Action\n\n# Autoriser un port entrant\nNew-NetFirewallRule -DisplayName "HTTP entrant" -Direction Inbound -Protocol TCP -LocalPort 80 -Action Allow\n\n# Bloquer une application\nNew-NetFirewallRule -DisplayName "Bloquer Telnet" -Direction Outbound `\n  -Program "C:\\Windows\\System32\\telnet.exe" -Action Block\n\n# Désactiver une règle\nDisable-NetFirewallRule -DisplayName "HTTP entrant"\n\n# Supprimer une règle\nRemove-NetFirewallRule -DisplayName "HTTP entrant"' },
          { type: 'info', content: '<strong>Ordre des règles iptables :</strong> les règles sont évaluées dans l\'ordre. La première correspondance gagne. Placer les règles ACCEPT avant les DROP généraux.' },
        ],
      },
      {
        id: 'vpn-vlan',
        titre: 'VPN et VLAN — Segmentation et Accès Distant',
        sections: [
          { type: 'h2', content: 'VPN — Réseau Privé Virtuel' },
          { type: 'p', content: 'Tunnel chiffré permettant de sécuriser les communications sur un réseau non sûr (Internet).' },
          { type: 'table', headers: ['Type VPN', 'Description', 'Usage'], rows: [
            ['Site-à-Site',         'Connecte deux réseaux distants en permanence',            'Liaison siège ↔ succursale'],
            ['Client-à-Site',       'Employé distant → réseau entreprise via VPN',             'Télétravail, accès nomade'],
            ['SSL/TLS VPN',         'Accès via navigateur HTTPS sans client lourd',            'Portail web sécurisé'],
          ]},
          { type: 'table', headers: ['Protocole', 'Port', 'Points forts'], rows: [
            ['OpenVPN',   'UDP 1194',       'Open source, très configurable, cross-platform'],
            ['WireGuard', 'UDP 51820',      'Moderne, ultra-rapide, code minimal (4000 lignes)'],
            ['IPsec',     'UDP 500 + 4500', 'Standard industriel, intégré aux routeurs/firewalls'],
            ['L2TP/IPsec','UDP 1701',       'Natif Windows, facile à déployer'],
          ]},
          { type: 'h2', content: 'VLAN — Segmentation logique du réseau' },
          { type: 'p', content: 'Les VLAN (Virtual LAN) isolent logiquement des groupes d\'équipements sur le même switch physique, améliorant sécurité et gestion.' },
          { type: 'table', headers: ['Concept', 'Description'], rows: [
            ['VLAN ID',             'Identifiant de 1 à 4094 (1 = natif/défaut, à éviter)'],
            ['Port d\'accès',       'Appartient à un seul VLAN — pour postes clients et serveurs'],
            ['Port Trunk',          'Transporte plusieurs VLANs — entre switches et routeurs'],
            ['Inter-VLAN routing',  'Routage entre VLANs via routeur ou switch de couche 3'],
            ['VLAN natif',          'VLAN non taggé sur un trunk — VLAN 1 par défaut (changer en prod)'],
          ]},
          { type: 'code', content: '! Configuration VLAN sur switch Cisco (IOS)\nvlan 10\n name VLAN-Informatique\nvlan 20\n name VLAN-Compta\nvlan 30\n name VLAN-DMZ\n\n! Port d\'accès VLAN 10\ninterface FastEthernet0/1\n switchport mode access\n switchport access vlan 10\n\n! Port Trunk entre switches\ninterface GigabitEthernet0/1\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30\n switchport trunk native vlan 99' },
          { type: 'h2', content: 'CIA Triad — Piliers de la sécurité' },
          { type: 'table', headers: ['Pilier', 'Description', 'Menaces typiques'], rows: [
            ['Confidentialité (C)', 'L\'information n\'est accessible qu\'aux personnes autorisées', 'Interception, écoute réseau, vol de données'],
            ['Intégrité (I)',       'L\'information ne peut être altérée sans autorisation',         'Modification, corruption, injection SQL'],
            ['Disponibilité (A)',   'L\'information est accessible quand nécessaire',                 'DoS/DDoS, panne, ransomware'],
          ]},
          { type: 'info', content: '<strong>Règle des 3-2-1 pour la sauvegarde :</strong> 3 copies des données, sur 2 supports différents, dont 1 hors site.' },
        ],
      },
    ],
    flashcards: [
      { id: 'sf1',  recto: 'Qu\'est-ce qu\'une CA (Certificate Authority) ?',         verso: 'Autorité de confiance qui signe et délivre les certificats numériques X.509.' },
      { id: 'sf2',  recto: 'Différence SSL et TLS ?',                                 verso: 'SSL est obsolète (vulnérabilités). TLS est son successeur sécurisé — TLS 1.3 est la version actuelle.' },
      { id: 'sf3',  recto: 'Commande pour afficher les règles iptables ?',            verso: 'iptables -L -v -n' },
      { id: 'sf4',  recto: 'Port par défaut d\'OpenVPN ?',                            verso: 'UDP 1194' },
      { id: 'sf5',  recto: 'Que signifie CIA Triad en sécurité ?',                    verso: 'Confidentialité, Intégrité, Disponibilité — les 3 piliers de la sécurité de l\'information.' },
      { id: 'sf6',  recto: 'Différence port Access et port Trunk VLAN ?',             verso: 'Access : un seul VLAN (clients). Trunk : plusieurs VLANs (entre switches/routeurs).' },
      { id: 'sf7',  recto: 'Qu\'est-ce qu\'un CSR ?',                                 verso: 'Certificate Signing Request — demande de certificat contenant la clé publique, envoyée à une CA.' },
      { id: 'sf8',  recto: 'Commande PowerShell pour créer une règle de pare-feu ?',  verso: 'New-NetFirewallRule -DisplayName "nom" -Direction Inbound -Protocol TCP -LocalPort 80 -Action Allow' },
      { id: 'sf9',  recto: 'Quel protocole VPN est le plus moderne et le plus léger ?', verso: 'WireGuard (UDP 51820) — code minimal, performances élevées, intégré au noyau Linux.' },
      { id: 'sf10', recto: 'Plage des VLAN IDs utilisables ?',                        verso: '1 à 4094 (VLAN 1 = natif par défaut, à éviter en production).' },
      { id: 'sf11', recto: 'Qu\'est-ce que TLS ?',                                    verso: 'Transport Layer Security — protocole de chiffrement des communications (successeur de SSL). Utilisé par HTTPS.' },
      { id: 'sf12', recto: 'Commande pour bloquer une IP avec iptables ?',            verso: 'iptables -A INPUT -s 192.168.1.100 -j DROP' },
      { id: 'sf13', recto: 'Qu\'est-ce qu\'un VPN site-à-site ?',                     verso: 'Tunnel chiffré permanent connectant deux réseaux distants (ex : siège ↔ succursale via IPsec).' },
      { id: 'sf14', recto: 'Que fait la politique DROP dans iptables ?',              verso: 'Rejette silencieusement les paquets qui ne correspondent à aucune règle ACCEPT. Plus sécurisé que REJECT.' },
      { id: 'sf15', recto: 'Port HTTPS ?',                                            verso: 'TCP 443' },
    ],
    qcm: [
      {
        id: 'sq1',
        question: 'Quel composant de la PKI est responsable de signer les certificats ?',
        options: [
          { text: 'Le CSR',                          correct: false },
          { text: 'La CA (Certificate Authority)',   correct: true  },
          { text: 'La CRL',                          correct: false },
          { text: 'Le certificat X.509',             correct: false },
        ],
        explication: 'La CA (Certificate Authority) est l\'autorité de confiance qui vérifie l\'identité du demandeur et signe le certificat avec sa clé privée.',
      },
      {
        id: 'sq2',
        question: 'Quel protocole VPN est le plus moderne, avec un code source minimal ?',
        options: [
          { text: 'OpenVPN',    correct: false },
          { text: 'L2TP/IPsec', correct: false },
          { text: 'WireGuard',  correct: true  },
          { text: 'PPTP',       correct: false },
        ],
        explication: 'WireGuard (UDP 51820) est conçu pour la simplicité et la performance. Son code source tient en ~4000 lignes, contre des centaines de milliers pour OpenVPN ou IPsec.',
      },
      {
        id: 'sq3',
        question: 'Quelle commande iptables affiche les règles actives avec les compteurs ?',
        options: [
          { text: 'iptables -show',   correct: false },
          { text: 'iptables -L -v -n', correct: true  },
          { text: 'iptables --list',  correct: false },
          { text: 'iptables -R',      correct: false },
        ],
        explication: 'iptables -L -v -n : -L liste les règles, -v affiche les compteurs (paquets/octets), -n affiche les IPs numériques sans résolution DNS.',
      },
      {
        id: 'sq4',
        question: 'Qu\'est-ce qu\'un port Trunk dans un réseau VLAN ?',
        options: [
          { text: 'Un port qui appartient à un seul VLAN',                  correct: false },
          { text: 'Un port qui transporte plusieurs VLANs simultanément',   correct: true  },
          { text: 'Un port de gestion du switch',                           correct: false },
          { text: 'Un port réservé au VLAN natif',                         correct: false },
        ],
        explication: 'Le port Trunk transporte le trafic de plusieurs VLANs en ajoutant un tag (802.1Q) à chaque trame. Utilisé entre switches et entre switch et routeur.',
      },
      {
        id: 'sq5',
        question: 'Quel pilier du CIA Triad est mis en danger par une attaque DoS ?',
        options: [
          { text: 'Confidentialité',  correct: false },
          { text: 'Intégrité',        correct: false },
          { text: 'Disponibilité',    correct: true  },
          { text: 'Authenticité',     correct: false },
        ],
        explication: 'Une attaque DoS/DDoS vise à rendre un service indisponible, attaquant le A de CIA (Availability). Elle ne vole ni ne modifie les données.',
      },
      {
        id: 'sq6',
        question: 'Quel port utilise OpenVPN par défaut ?',
        options: [
          { text: 'TCP 1194',  correct: false },
          { text: 'UDP 51820', correct: false },
          { text: 'UDP 1194',  correct: true  },
          { text: 'TCP 443',   correct: false },
        ],
        explication: 'OpenVPN utilise UDP 1194 par défaut. Il peut aussi fonctionner sur TCP 443 pour contourner les pare-feu restrictifs.',
      },
      {
        id: 'sq7',
        question: 'Quelle commande PowerShell liste les règles de pare-feu Windows actives ?',
        options: [
          { text: 'Show-NetFirewallRule',  correct: false },
          { text: 'Get-NetFirewallRule',   correct: true  },
          { text: 'List-FirewallRules',    correct: false },
          { text: 'Get-WindowsFirewall',   correct: false },
        ],
        explication: 'Get-NetFirewallRule liste toutes les règles. Ajouter | Where-Object {$_.Enabled -eq "True"} pour filtrer les règles actives.',
      },
      {
        id: 'sq8',
        question: 'Quel type de pare-feu analyse les connexions dans leur ensemble (pas juste les paquets individuels) ?',
        options: [
          { text: 'Stateless',    correct: false },
          { text: 'ACL Cisco',    correct: false },
          { text: 'Stateful',     correct: true  },
          { text: 'Routeur NAT',  correct: false },
        ],
        explication: 'Un pare-feu stateful suit l\'état des connexions (NEW, ESTABLISHED, RELATED). Il accepte automatiquement les paquets de retour des connexions initiées de l\'intérieur.',
      },
    ],
  },
];
