// data.js — Structure des modules TSSR

const MODULES = [
  {
    id: 'numerisation',
    label: 'Numération',
    icon: '🔢',
    color: '#00ff88',
    desc: 'Systèmes de numération : binaire, octal, hexadécimal, conversions...',
    topics: [],
    outils: 'modules/numerisation/outils.html',
    cours: [
      {
        id: 'cours_optimise_claude',
        titre: 'Architecture des Données : Encodage, Systèmes de Numération et Logique Booléenne',
        sections: [
          { type: 'html-file', src: 'modules/numerisation/cours_optimise_claude.html' },
        ],
      },
    ],
    flashcards: [],
    qcm: [],
  },
  {
    id: 'reseaux',
    label: 'Réseaux',
    icon: '🌐',
    color: '#3b82f6',
    desc: 'Modèle OSI, TCP/IP, adressage IP, sous-réseaux, services réseau...',
    topics: ['OSI', 'TCP/IP', 'Adressage IP', 'VLAN', 'DNS', 'DHCP', 'Routage'],
    cours: [
      {
        id: 'modele-osi',
        titre: 'Modèle OSI — 7 Couches',
        sections: [],
      },
      {
        id: 'cours_reseaux',
        titre: 'Réseaux : OSI, TCP/IP, Adressage et Services',
        sections: [{ type: 'html-file', src: 'modules/reseaux/cours_reseaux.html' }],
      },
    ],
    flashcards: [],
    qcm: [],
    linux_cli: true,
    windows_cli: true,
  },
  {
    id: 'linux',
    label: 'Linux',
    icon: '🐧',
    color: '#00ff88',
    desc: 'Commandes, droits, services, filtrage, gestion de paquets...',
    topics: ['Système de fichiers', 'VIM', 'Droits', 'Processus', 'APT', 'Redirections'],
    cours: [
      {
        id: 'encyclopedie-linux',
        titre: 'Encyclopédie Linux — Formation TSSR',
        sections: [

          // 1. Installation & Philosophie
          { type: 'h2', content: '1. Installation &amp; Philosophie' },
          { type: 'p', content: 'Linux est un noyau open-source utilisé dans la majorité des serveurs, équipements réseau et systèmes embarqués. En formation TSSR, on travaille généralement sous Debian/Ubuntu dans une machine virtuelle (VirtualBox ou VMware).' },
          { type: 'info', content: '<strong>Virtualisation :</strong> une VM Linux s\'installe depuis une image ISO. On choisit la langue, le partitionnement (ext4 recommandé) et un utilisateur non-root dès l\'installation.' },
          { type: 'table', headers: ['Compte', 'Rôle', 'Invite de commande'], rows: [
            ['root', 'Super-administrateur, droits illimités', '<code>#</code>'],
            ['utilisateur', 'Compte courant, droits limités', '<code>$</code>'],
          ]},
          { type: 'warn', content: '<strong>Ne jamais travailler en root au quotidien.</strong> Utiliser <code>sudo</code> pour élever les privilèges ponctuellement.' },
          { type: 'code', content: 'sudo apt update          # exécute apt en tant que root\nsudo -i                  # ouvre un shell root (quitter avec exit)\nwhoami                   # affiche l\'utilisateur courant\nid                       # UID, GID et groupes' },

          // 2. Navigation & Système de fichiers
          { type: 'h2', content: '2. Navigation &amp; Système de fichiers' },
          { type: 'p', content: 'Linux utilise une arborescence unique enracinée en <code>/</code>. Pas de lettres de lecteur comme sous Windows : tout est monté sous la racine.' },
          { type: 'table', headers: ['Répertoire', 'Contenu'], rows: [
            ['<code>/</code>',     'Racine du système'],
            ['<code>/etc</code>',  'Fichiers de configuration système'],
            ['<code>/home</code>', 'Répertoires personnels des utilisateurs'],
            ['<code>/var</code>',  'Données variables (logs, bases, cache)'],
            ['<code>/bin</code>',  'Binaires essentiels (ls, cp, mv…)'],
            ['<code>/usr</code>',  'Applications installées'],
            ['<code>/tmp</code>',  'Fichiers temporaires (vidés au reboot)'],
            ['<code>/proc</code>', 'Pseudo-FS : infos noyau/processus en temps réel'],
          ]},
          { type: 'code', content: 'pwd                      # affiche le répertoire courant\nls                       # liste les fichiers\nls -l                    # format long (droits, taille, date)\nls -la                   # idem + fichiers cachés (commençant par .)\nls -lh                   # tailles lisibles (Ko, Mo)\ncd /etc                  # aller dans /etc\ncd ~                     # aller dans son home\ncd ..                    # remonter d\'un niveau\ncd -                     # revenir au répertoire précédent\ntree                     # arborescence graphique (si installé)' },
          { type: 'info', content: '<strong>Chemin absolu vs relatif :</strong> <code>/home/user/docs</code> est absolu (part de /). <code>../docs</code> est relatif (part du répertoire courant).' },

          // 3. Manipulation de fichiers
          { type: 'h2', content: '3. Manipulation de fichiers' },
          { type: 'code', content: 'mkdir dossier            # créer un répertoire\nmkdir -p a/b/c           # créer l\'arborescence complète\ntouch fichier.txt        # créer un fichier vide (ou mettre à jour la date)\ncp source dest           # copier un fichier\ncp -r src/ dest/         # copier un dossier (récursif)\nmv ancien nouveau        # déplacer ou renommer\nrm fichier               # supprimer un fichier\nrm -r dossier/           # supprimer un dossier et son contenu\nrm -rf dossier/          # idem, sans confirmation (dangereux)' },
          { type: 'warn', content: '<strong>rm -rf</strong> est irréversible. Il n\'y a pas de corbeille en ligne de commande. Vérifier deux fois avant d\'exécuter.' },
          { type: 'code', content: 'cat fichier.txt          # afficher le contenu\nless fichier.txt         # affichage page par page (q pour quitter)\nhead -n 5 fichier.txt    # 5 premières lignes\ntail -n 5 fichier.txt    # 5 dernières lignes\ntail -f /var/log/syslog  # suivre un fichier en temps réel\nwc -l fichier.txt        # compter les lignes\nfile fichier             # type du fichier' },

          // 4. Édition VIM
          { type: 'h2', content: '4. Édition VIM' },
          { type: 'p', content: 'VIM est l\'éditeur de texte en ligne de commande incontournable. Il fonctionne par modes : on ne tape pas directement comme dans un éditeur graphique.' },
          { type: 'table', headers: ['Mode', 'Description', 'Accès'], rows: [
            ['Normal',    'Navigation, copier/coller, suppression', 'Touche <code>Échap</code>'],
            ['Insertion', 'Saisie de texte',                        '<code>i</code> (avant curseur), <code>a</code> (après), <code>o</code> (nouvelle ligne)'],
            ['Commande',  'Sauvegarder, quitter, rechercher',       '<code>:</code> depuis le mode Normal'],
          ]},
          { type: 'steps', items: [
            { num: '1', title: 'Ouvrir un fichier',         code: 'vim fichier.txt' },
            { num: '2', title: 'Passer en mode insertion',  content: 'Appuyer sur <kbd>i</kbd>' },
            { num: '3', title: 'Écrire du texte',           content: 'Saisir normalement' },
            { num: '4', title: 'Revenir en mode normal',    content: 'Appuyer sur <kbd>Échap</kbd>' },
            { num: '5', title: 'Sauvegarder et quitter',    code: ':wq' },
          ]},
          { type: 'table', headers: ['Commande', 'Action'], rows: [
            ['<code>:w</code>',    'Sauvegarder'],
            ['<code>:q</code>',    'Quitter (si pas de modification)'],
            ['<code>:wq</code>',   'Sauvegarder et quitter'],
            ['<code>:q!</code>',   'Quitter sans sauvegarder (forcer)'],
            ['<code>/mot</code>',  'Rechercher "mot" (n = occurrence suivante)'],
            ['<code>dd</code>',    'Supprimer la ligne courante (mode normal)'],
            ['<code>yy</code>',    'Copier la ligne (yank)'],
            ['<code>p</code>',     'Coller après le curseur'],
            ['<code>u</code>',     'Annuler (undo)'],
            ['<code>Ctrl+r</code>','Rétablir (redo)'],
          ]},

          // 5. Droits Linux
          { type: 'h2', content: '5. Droits Linux' },
          { type: 'p', content: 'Chaque fichier a des droits pour 3 entités : le propriétaire (u), le groupe (g), et les autres (o). Les droits sont r (lecture), w (écriture), x (exécution).' },
          { type: 'table', headers: ['Droit', 'Lettre', 'Valeur octale'], rows: [
            ['Lecture',    'r', '4'],
            ['Écriture',   'w', '2'],
            ['Exécution',  'x', '1'],
            ['Aucun droit','—', '0'],
          ]},
          { type: 'info', content: '<strong>Lecture rapide de chmod :</strong> <code>755</code> = rwxr-xr-x (propriétaire : tout ; groupe et autres : lecture + exécution). <code>644</code> = rw-r--r-- (fichier de config type).' },
          { type: 'code', content: 'ls -l fichier.txt\n# -rw-r--r-- 1 alice staff 1024 juin  9 10:00 fichier.txt\n#  ^^^       ^\n#  droits    |— nb liens\n#  u=rw g=r o=r\n\nchmod 755 script.sh      # rwxr-xr-x\nchmod +x  script.sh      # ajouter exécution à tous\nchmod u+w fichier.txt    # ajouter écriture au propriétaire\nchmod o-r fichier.txt    # retirer lecture aux autres\n\nchown alice fichier.txt         # changer propriétaire\nchown alice:staff fichier.txt   # changer propriétaire et groupe\nchgrp staff fichier.txt         # changer groupe uniquement' },

          // 6. Redirections & Flux
          { type: 'h2', content: '6. Redirections &amp; Flux' },
          { type: 'table', headers: ['Flux', 'Numéro', 'Description'], rows: [
            ['stdin',  '0', 'Entrée standard (clavier par défaut)'],
            ['stdout', '1', 'Sortie standard (terminal par défaut)'],
            ['stderr', '2', 'Sortie d\'erreur (terminal par défaut)'],
          ]},
          { type: 'code', content: 'ls > liste.txt           # redirige stdout vers fichier (écrase)\nls >> liste.txt          # redirige stdout (ajoute)\nls 2> erreurs.txt        # redirige stderr vers fichier\nls > tout.txt 2>&1       # redirige stdout ET stderr\nls 2>/dev/null           # jeter les erreurs\ncat < fichier.txt        # stdin depuis fichier\ncommande1 | commande2    # pipe : stdout1 → stdin2\necho "texte" | wc -c    # compter les caractères via pipe' },
          { type: 'info', content: '<strong>Chaîner avec pipes :</strong> <code>cat /etc/passwd | grep bash | cut -d: -f1</code> — affiche les utilisateurs avec bash comme shell.' },

          // 7. Gestion processus & services
          { type: 'h2', content: '7. Gestion des processus &amp; services' },
          { type: 'h3', content: 'Processus' },
          { type: 'code', content: 'ps aux                   # liste tous les processus\nps aux | grep nginx      # filtrer par nom\ntop                      # moniteur interactif (q pour quitter)\nhtop                     # version améliorée (si installé)\nkill 1234                # envoyer SIGTERM au PID 1234\nkill -9 1234             # forcer la fin (SIGKILL)\npkill nginx              # tuer par nom\nkillall nginx            # tuer toutes les instances\nnohup cmd &              # lancer en arrière-plan, immunisé au logout' },
          { type: 'code', content: 'commande &               # lancer en arrière-plan\njobs                     # lister les tâches en arrière-plan\nfg %1                    # ramener la tâche 1 au premier plan\nbg %1                    # reprendre la tâche 1 en arrière-plan\nCtrl+Z                   # suspendre la commande en cours\nCtrl+C                   # interrompre la commande en cours' },
          { type: 'h3', content: 'Services (systemd)' },
          { type: 'code', content: 'systemctl status ssh              # état du service ssh\nsystemctl start  ssh             # démarrer\nsystemctl stop   ssh             # arrêter\nsystemctl restart ssh            # redémarrer\nsystemctl enable  ssh            # activer au démarrage\nsystemctl disable ssh            # désactiver au démarrage\nsystemctl list-units --type=service   # lister les services\njournalctl -u ssh                # logs du service ssh\njournalctl -f                    # suivre les logs en temps réel' },

          // 8. Filtrage & Traitement
          { type: 'h2', content: '8. Filtrage &amp; Traitement de texte' },
          { type: 'h3', content: 'grep — rechercher des lignes' },
          { type: 'code', content: 'grep "motif" fichier.txt         # lignes contenant "motif"\ngrep -i "motif" fichier.txt      # insensible à la casse\ngrep -r "motif" /etc/            # récursif dans un dossier\ngrep -v "motif" fichier.txt      # lignes NE contenant PAS "motif"\ngrep -n "motif" fichier.txt      # afficher les numéros de ligne\ngrep -c "motif" fichier.txt      # compter les occurrences\ngrep -E "^root|^alice" /etc/passwd  # regex étendue' },
          { type: 'h3', content: 'cut — extraire des colonnes' },
          { type: 'code', content: 'cut -d: -f1 /etc/passwd          # 1er champ, délimiteur :\ncut -d: -f1,3 /etc/passwd        # champs 1 et 3\ncut -c1-10 fichier.txt           # caractères 1 à 10 de chaque ligne' },
          { type: 'h3', content: 'sed — remplacer du texte' },
          { type: 'code', content: 'sed "s/ancien/nouveau/" fichier.txt    # remplace 1ère occurrence par ligne\nsed "s/ancien/nouveau/g" fichier.txt   # remplace toutes les occurrences\nsed -i "s/foo/bar/g" fichier.txt       # modifie le fichier en place\nsed "/^#/d" fichier.txt                # supprime les lignes commençant par #' },
          { type: 'h3', content: 'awk — traitement structuré' },
          { type: 'code', content: 'awk "{print $1}" fichier.txt      # affiche le 1er champ (séparateur espace)\nawk -F: "{print $1,$3}" /etc/passwd   # séparateur :, champs 1 et 3\nawk "$3 > 1000" /etc/passwd      # lignes où le champ 3 > 1000\nawk "END{print NR}" fichier.txt  # compter le nombre de lignes' },

          // 9. Gestion des paquets APT
          { type: 'h2', content: '9. Gestion des paquets — APT' },
          { type: 'p', content: 'APT (Advanced Package Tool) est le gestionnaire de paquets de Debian/Ubuntu. Il télécharge et installe les logiciels depuis des dépôts officiels.' },
          { type: 'steps', items: [
            { num: '1', title: 'Mettre à jour la liste des paquets', code: 'sudo apt update', why: 'Synchronise la liste locale avec les dépôts — à faire avant toute installation.' },
            { num: '2', title: 'Mettre à jour les paquets installés', code: 'sudo apt upgrade', why: 'Installe les nouvelles versions de tous les paquets existants.' },
            { num: '3', title: 'Installer un paquet',                code: 'sudo apt install vim',  why: 'Télécharge et installe vim et ses dépendances.' },
            { num: '4', title: 'Désinstaller un paquet',             code: 'sudo apt remove vim',   why: 'Supprime le paquet mais garde les fichiers de configuration.' },
            { num: '5', title: 'Désinstaller + config',              code: 'sudo apt purge vim',    why: 'Supprime le paquet ET ses fichiers de configuration.' },
            { num: '6', title: 'Nettoyer les paquets orphelins',     code: 'sudo apt autoremove',   why: 'Supprime les dépendances devenues inutiles.' },
          ]},
          { type: 'code', content: 'apt search nginx                 # rechercher un paquet\napt show nginx                   # informations sur un paquet\ndpkg -l | grep nginx             # vérifier si installé\ndpkg -L nginx                    # lister les fichiers du paquet\napt list --installed             # tous les paquets installés\napt-cache policy nginx           # version installée vs disponible' },
          { type: 'info', content: '<strong>Rappel :</strong> toujours faire <code>sudo apt update</code> avant <code>apt install</code>, sinon APT peut proposer une version obsolète.' },

        ],
      },
    ],
    flashcards: [],
    qcm: [],
    linux_cli: true,
    gameshell: true,
  },
  {
    id: 'linux-server',
    label: 'Serveur Linux',
    icon: '🐧',
    color: '#00e5a0',
    desc: 'Administration serveur Debian/Ubuntu, Apache, SSH, Samba, pare-feu...',
    topics: ['SSH', 'Apache', 'Samba', 'UFW', 'Cron', 'Logs'],
    linux_cli: true,
    cours: [
      {
        id: 'admin-linux-base',
        titre: 'Administration Serveur Linux — Les Fondamentaux',
        sections: [
          { type: 'h2', content: 'Gestion des utilisateurs' },
          { type: 'code', content: '# Créer un utilisateur avec home\nuseradd -m -s /bin/bash anthony\npasswd anthony\n\n# Ajouter au groupe sudo\nusermod -aG sudo anthony\n\n# Voir les groupes d\'un utilisateur\ngroups anthony\n\n# Supprimer un utilisateur\nuserdel -r anthony' },
          { type: 'h2', content: 'Gestion des services (systemd)' },
          { type: 'code', content: '# Démarrer / arrêter / redémarrer\nsystemctl start apache2\nsystemctl stop apache2\nsystemctl restart apache2\n\n# Activer au démarrage\nsystemctl enable apache2\n\n# Voir le statut détaillé\nsystemctl status apache2\n\n# Lister tous les services actifs\nsystemctl list-units --type=service --state=active' },
          { type: 'h2', content: 'Surveillance du système' },
          { type: 'code', content: '# Espace disque\ndf -h\n\n# Utilisation RAM\nfree -h\n\n# Charge CPU\ntop\nhtop  # plus lisible (apt install htop)\n\n# Processus d\'un service\nps aux | grep apache2\n\n# Logs système en temps réel\njournalctl -f\ntail -f /var/log/syslog' },
          { type: 'h2', content: 'Gestion des paquets (APT)' },
          { type: 'code', content: 'apt update && apt upgrade -y\napt install apache2 -y\napt remove apache2\napt autoremove\ndpkg -l | grep apache  # lister les paquets installés' },
          { type: 'h2', content: 'Planification des tâches (Cron)' },
          { type: 'code', content: '# Éditer la crontab de l\'utilisateur courant\ncrontab -e\n\n# Format : minute heure jour mois jour_semaine commande\n# Exemple : sauvegarde tous les jours à 2h00\n0 2 * * * /usr/local/bin/backup.sh >> /var/log/backup.log 2>&1\n\n# Lister les tâches planifiées\ncrontab -l' },
        ],
      },
      {
        id: 'services-reseau-linux',
        titre: 'Services Réseau Linux — SSH, Apache, Samba',
        sections: [
          { type: 'h2', content: 'SSH — Accès distant sécurisé' },
          { type: 'p', content: 'SSH (Secure Shell) permet l\'administration distante sécurisée via chiffrement.' },
          { type: 'code', content: '# Installer le serveur SSH\napt install openssh-server\nsystemctl enable --now ssh\n\n# Se connecter depuis un client\nssh anthony@192.168.1.10\nssh -p 2222 anthony@192.168.1.10  # port personnalisé\n\n# Configurer SSH (/etc/ssh/sshd_config)\nPort 22\nPermitRootLogin no          # Désactiver connexion root directe\nPasswordAuthentication yes\nMaxAuthTries 3\n\n# Redémarrer après modification\nsystemctl restart ssh' },
          { type: 'warn', content: 'Toujours désactiver PermitRootLogin et changer le port par défaut en production.' },
          { type: 'h2', content: 'Apache2 — Serveur Web' },
          { type: 'code', content: 'apt install apache2\nsystemctl enable --now apache2\n\n# Tester localement\ncurl http://localhost\n\n# Fichiers de configuration\n# Site par défaut : /etc/apache2/sites-available/000-default.conf\n# Racine web : /var/www/html/\n\n# Activer/désactiver un site\na2ensite monsite.conf\na2dissite 000-default.conf\nsystemctl reload apache2\n\n# Logs Apache\ntail -f /var/log/apache2/access.log\ntail -f /var/log/apache2/error.log' },
          { type: 'h2', content: 'Samba — Partage de fichiers Windows/Linux' },
          { type: 'code', content: 'apt install samba\n\n# Configurer /etc/samba/smb.conf\n[partage]\npath = /srv/partage\nbrowseable = yes\nread only = no\nvalid users = anthony\n\n# Créer le dossier et les droits\nmkdir -p /srv/partage\nchown anthony:anthony /srv/partage\nchmod 770 /srv/partage\n\n# Créer un utilisateur Samba\nsmbpasswd -a anthony\nsystemctl restart smbd' },
          { type: 'h2', content: 'UFW — Pare-feu simplifié' },
          { type: 'code', content: '# Activer UFW\nufw enable\n\n# Autoriser SSH (AVANT d\'activer !)\nufw allow ssh\nufw allow 22/tcp\n\n# Autoriser HTTP et HTTPS\nufw allow 80/tcp\nufw allow 443/tcp\n\n# Voir les règles\nufw status verbose\n\n# Supprimer une règle\nufw delete allow 80/tcp' },
        ],
      },
      {
        id: 'securite-logs-linux',
        titre: 'Sécurité et Analyse des Logs Linux',
        sections: [
          { type: 'h2', content: 'Fichiers de logs essentiels' },
          { type: 'table', headers: ['Fichier', 'Contenu'], rows: [
            ['<code>/var/log/syslog</code>',             'Logs système généraux'],
            ['<code>/var/log/auth.log</code>',           'Authentifications et sudo'],
            ['<code>/var/log/apache2/access.log</code>', 'Requêtes HTTP reçues'],
            ['<code>/var/log/apache2/error.log</code>',  'Erreurs Apache'],
            ['<code>/var/log/dpkg.log</code>',           'Installations de paquets'],
          ]},
          { type: 'code', content: '# Rechercher les échecs de connexion SSH\ngrep "Failed password" /var/log/auth.log\n\n# Voir les connexions réussies\ngrep "Accepted" /var/log/auth.log\n\n# Analyser avec journalctl\njournalctl -u ssh --since "2024-01-01" --until "2024-12-31"\njournalctl -p err  # uniquement les erreurs' },
          { type: 'h2', content: 'Fail2ban — Protection contre les attaques brute force' },
          { type: 'code', content: 'apt install fail2ban\n\n# Configuration /etc/fail2ban/jail.local\n[sshd]\nenabled = true\nmaxretry = 3\nbantime = 3600\nfindtime = 600\n\nsystemctl enable --now fail2ban\n\n# Voir les IPs bannies\nfail2ban-client status sshd' },
          { type: 'h2', content: 'Sudo et élévation de privilèges' },
          { type: 'code', content: '# Éditer sudoers (toujours via visudo !)\nvisudo\n\n# Autoriser un utilisateur à tout faire\nanthony ALL=(ALL:ALL) ALL\n\n# Autoriser sans mot de passe (déconseillé)\nanthony ALL=(ALL) NOPASSWD: ALL\n\n# Autoriser seulement certaines commandes\nanthony ALL=(ALL) /bin/systemctl, /usr/bin/apt' },
        ],
      },
    ],
    flashcards: [
      { id: 'lsf1',  recto: 'Commande pour voir les logs en temps réel ?',        verso: 'journalctl -f  ou  tail -f /var/log/syslog' },
      { id: 'lsf2',  recto: 'Comment ajouter un utilisateur au groupe sudo ?',    verso: 'usermod -aG sudo username' },
      { id: 'lsf3',  recto: 'Commande pour activer un service au démarrage ?',    verso: 'systemctl enable nom_service' },
      { id: 'lsf4',  recto: 'Où se trouve la config SSH serveur ?',               verso: '/etc/ssh/sshd_config' },
      { id: 'lsf5',  recto: 'Commande pour voir l\'espace disque ?',              verso: 'df -h (disques) et du -sh dossier (taille d\'un dossier)' },
      { id: 'lsf6',  recto: 'Qu\'est-ce que Fail2ban ?',                          verso: 'Outil qui bannit automatiquement les IPs après X tentatives de connexion échouées' },
      { id: 'lsf7',  recto: 'Port par défaut SSH ?',                              verso: 'Port 22 TCP' },
      { id: 'lsf8',  recto: 'Commande pour éditer la crontab ?',                  verso: 'crontab -e (utilisateur courant) ou crontab -e -u username (autre user)' },
      { id: 'lsf9',  recto: 'Format d\'une ligne crontab ?',                      verso: 'minute heure jour mois jour_semaine commande (ex: 0 2 * * * /script.sh)' },
      { id: 'lsf10', recto: 'Commande pour autoriser SSH dans UFW ?',             verso: 'ufw allow ssh  ou  ufw allow 22/tcp' },
      { id: 'lsf11', recto: 'Où se trouvent les sites Apache ?',                  verso: '/etc/apache2/sites-available/ (disponibles) et sites-enabled/ (actifs)' },
      { id: 'lsf12', recto: 'Commande pour créer un utilisateur Samba ?',         verso: 'smbpasswd -a username' },
      { id: 'lsf13', recto: 'Logs d\'authentification Linux ?',                   verso: '/var/log/auth.log' },
      { id: 'lsf14', recto: 'Comment voir la RAM utilisée ?',                     verso: 'free -h' },
      { id: 'lsf15', recto: 'Commande pour voir tous les services actifs ?',      verso: 'systemctl list-units --type=service --state=active' },
    ],
    qcm: [
      {
        id: 'lsq1',
        question: 'Quel fichier contient la configuration du serveur SSH ?',
        options: [
          { text: '/etc/ssh/ssh_config',  correct: false },
          { text: '/etc/ssh/sshd_config', correct: true  },
          { text: '/etc/sshd/config',     correct: false },
          { text: '/usr/ssh/config',      correct: false },
        ],
        explication: 'sshd_config configure le serveur SSH (sshd). ssh_config configure le client SSH.',
      },
      {
        id: 'lsq2',
        question: 'Quelle commande active UFW ?',
        options: [
          { text: 'ufw start',           correct: false },
          { text: 'ufw enable',          correct: true  },
          { text: 'systemctl start ufw', correct: false },
          { text: 'iptables -A UFW',     correct: false },
        ],
        explication: 'ufw enable active le pare-feu UFW et le configure pour démarrer au boot.',
      },
      {
        id: 'lsq3',
        question: 'Où se trouvent les fichiers web par défaut d\'Apache2 ?',
        options: [
          { text: '/etc/apache2/',       correct: false },
          { text: '/usr/share/apache2/', correct: false },
          { text: '/var/www/html/',      correct: true  },
          { text: '/srv/www/',           correct: false },
        ],
        explication: '/var/www/html/ est la racine web par défaut d\'Apache2 sur Debian/Ubuntu.',
      },
      {
        id: 'lsq4',
        question: 'Quelle commande liste les tâches cron de l\'utilisateur courant ?',
        options: [
          { text: 'cron -l',               correct: false },
          { text: 'crontab -l',            correct: true  },
          { text: 'cat /etc/crontab',      correct: false },
          { text: 'systemctl status cron', correct: false },
        ],
        explication: 'crontab -l liste les tâches planifiées de l\'utilisateur courant. /etc/crontab est la crontab système.',
      },
      {
        id: 'lsq5',
        question: 'Quel fichier de log contient les tentatives de connexion SSH échouées ?',
        options: [
          { text: '/var/log/syslog',   correct: false },
          { text: '/var/log/messages', correct: false },
          { text: '/var/log/auth.log', correct: true  },
          { text: '/var/log/ssh.log',  correct: false },
        ],
        explication: '/var/log/auth.log contient toutes les authentifications (SSH, sudo, su) réussies et échouées.',
      },
      {
        id: 'lsq6',
        question: 'Comment redémarrer Apache après modification de sa config ?',
        options: [
          { text: 'apache2 restart',           correct: false },
          { text: 'systemctl restart apache2', correct: true  },
          { text: 'service apache reload',     correct: false },
          { text: 'apachectl -k reboot',       correct: false },
        ],
        explication: 'systemctl restart apache2 arrête et redémarre Apache. systemctl reload recharge la config sans coupure.',
      },
      {
        id: 'lsq7',
        question: 'Quelle commande Samba crée un utilisateur Samba ?',
        options: [
          { text: 'adduser samba username',      correct: false },
          { text: 'smbpasswd -a username',       correct: true  },
          { text: 'net user username /add',      correct: false },
          { text: 'samba-user -create username', correct: false },
        ],
        explication: 'smbpasswd -a crée un compte Samba pour l\'utilisateur. Le compte Linux doit exister au préalable.',
      },
      {
        id: 'lsq8',
        question: 'Quelle option de sshd_config désactive la connexion root directe ?',
        options: [
          { text: 'RootLogin no',       correct: false },
          { text: 'PermitRoot false',   correct: false },
          { text: 'PermitRootLogin no', correct: true  },
          { text: 'DenyRoot yes',       correct: false },
        ],
        explication: 'PermitRootLogin no dans sshd_config empêche la connexion SSH directe en root. Bonne pratique de sécurité.',
      },
    ],
  },
  {
    id: 'windows',
    label: 'Windows',
    icon: '🪟',
    color: '#0ea5e9',
    desc: 'Gestion des disques, SAM, droits NTFS, pare-feu, BitLocker...',
    topics: ['Diskpart', 'SAM', 'NTFS', 'icacls', 'BitLocker', 'Pare-feu'],
    cours: [
      {
        id: 'cours_windows_objectifs',
        titre: 'Administration Windows : Disques, SAM, NTFS et Sécurisation',
        sections: [
          { type: 'html-file', src: 'modules/windows/cours_windows_objectifs.html' },
        ],
      },
      {
        id: 'admin-windows-test',
        titre: 'Administration Windows — CMD & PowerShell',
        badge: 'test',
        sections: [
          { type: 'h2', content: '1. Gestion des Utilisateurs et Groupes (CMD - Net)' },
          { type: 'warn', content: 'L\'invite de commande doit être lancée en mode Administrateur.' },
          { type: 'ul', items: [
            '<code>net user Anthony P@ssword123 /add</code> : Crée un compte utilisateur.',
            '<code>net localgroup Support /add</code> : Crée un groupe local nommé "Support".',
            '<code>net localgroup Support Anthony /add</code> : Ajoute l\'utilisateur au groupe.',
            '<code>net user Anthony</code> : Affiche les informations complètes du compte.',
          ]},
          { type: 'h2', content: '2. Gestion des Disques (Diskpart)' },
          { type: 'warn', content: '<strong>ATTENTION :</strong> La commande <code>clean</code> supprime toutes les données du disque sélectionné.' },
          { type: 'code', content: 'diskpart               # Lance l\'outil\nlist disk              # Liste les disques physiques\nselect disk 0          # Sélectionne le disque 0\nclean                  # Efface toute la structure\ncreate partition primary size=50000  # Partition de 50Go\nformat fs=ntfs quick   # Formatage rapide\nassign letter=E        # Monte le disque en E:' },
          { type: 'h2', content: '3. Administration Domaine (Active Directory)' },
          { type: 'ul', items: [
            '<code>wmic computersystem get domain</code> : Vérifie à quel domaine appartient la machine.',
            '<code>Add-Computer -DomainName "carrefour.local" -Credential (Get-Credential)</code> : Joint la machine au domaine (PowerShell).',
          ]},
          { type: 'h2', content: '4. PowerShell — Cmdlets essentielles' },
          { type: 'info', content: 'Syntaxe basée sur <strong>Verbe-Nom</strong>. Les résultats sont des objets manipulables.' },
          { type: 'ul', items: [
            '<code>Get-Process</code> : Liste les processus.',
            '<code>Stop-Process -Name "chrome" -Force</code> : Tue un processus par son nom.',
            '<code>Get-Service</code> : Liste les services Windows.',
            '<code>Restart-Service -Name "wuauserv"</code> : Redémarre Windows Update.',
            '<strong>Pipe :</strong> <code>Get-Process | Where-Object {$_.CPU -gt 100}</code> : Filtre les processus gourmands en CPU.',
          ]},
          { type: 'h2', content: '5. Diagnostic Réseau' },
          { type: 'table', headers: ['Problème', 'Commande'], rows: [
            ['Info IP/DNS/DHCP', '<code>ipconfig /all</code>'],
            ['Vérifier connectivité', '<code>ping 8.8.8.8</code>'],
            ['Vérifier résolution DNS', '<code>nslookup google.com</code>'],
            ['Vider cache DNS', '<code>ipconfig /flushdns</code>'],
            ['Chemin réseau', '<code>route print</code>'],
          ]},
          { type: 'h2', content: '6. Quiz rapide' },
          { type: 'ul', items: [
            'Redémarrer le service DNS ? → <code>Restart-Service Dnscache</code>',
            'Lister les disques via diskpart ? → <code>list disk</code>',
            'Tuer un processus par son nom ? → <code>taskkill /F /IM nom.exe</code>',
          ]},
        ],
      },
    ],
    flashcards: [],
    qcm: [],
    windows_cli: true,
    netrunner: true,
  },
  {
    id: 'windows-server',
    label: 'Windows Server 2025',
    icon: '🖥️',
    color: '#0ea5e9',
    desc: 'Installation, configuration, Active Directory, GPO, DNS, DHCP...',
    topics: ['Installation', 'AD DS', 'GPO', 'DNS', 'DHCP', 'IIS', 'RDS'],
    windows_cli: true,
    cours: [
      {
        id: 'install-ws2025',
        titre: 'Installation Windows Server 2025',
        sections: [
          { type: 'h2', content: 'Prérequis matériels' },
          { type: 'table', headers: ['Composant', 'Minimum', 'Recommandé'], rows: [
            ['CPU',    '2 GHz 64 bits',  '2 GHz 64 bits (multicœur)'],
            ['RAM',    '2 Go',            '16 Go'],
            ['Disque', '32 Go',           '100 Go'],
            ['Réseau', 'Carte Ethernet',  'Carte Ethernet Gigabit'],
          ]},
          { type: 'h2', content: 'Éditions disponibles' },
          { type: 'table', headers: ['Édition', 'Description'], rows: [
            ['Standard',   'Virtualisation limitée : 2 VMs incluses'],
            ['Datacenter', 'VMs illimitées — environnements cloud et datacenter'],
            ['Essentials', '25 utilisateurs max — petites structures'],
          ]},
          { type: 'h2', content: 'Processus d\'installation pas à pas' },
          { type: 'steps', items: [
            { num: '1', title: 'Démarrer depuis l\'ISO',         content: 'Sélectionner la langue, le fuseau horaire et la disposition du clavier.' },
            { num: '2', title: 'Choisir l\'édition',             content: '<strong>Standard avec interface graphique</strong> (Desktop Experience) recommandé pour débuter.' },
            { num: '3', title: 'Type d\'installation',           content: '<strong>Personnalisée</strong> — nouvelle installation propre sur le disque cible.' },
            { num: '4', title: 'Partitionnement',                content: 'Créer une partition système de <strong>100 Go minimum</strong>.' },
            { num: '5', title: 'Mot de passe Administrateur',    content: 'Minimum 12 caractères — majuscule + chiffre + symbole obligatoire.' },
            { num: '6', title: 'Configuration post-installation', content: 'Renommer le serveur, configurer l\'IP fixe, activer Windows Update.' },
          ]},
          { type: 'h2', content: 'Configuration IP fixe (PowerShell)' },
          { type: 'code', content: 'New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress 192.168.1.10 -PrefixLength 24 -DefaultGateway 192.168.1.1\nSet-DnsClientServerAddress -InterfaceAlias "Ethernet" -ServerAddresses 192.168.1.10' },
          { type: 'h2', content: 'Renommer le serveur' },
          { type: 'code', content: 'Rename-Computer -NewName "SRV-TSSR-01" -Restart' },
          { type: 'warn', content: 'Toujours configurer une IP fixe avant de promouvoir en contrôleur de domaine.' },
          { type: 'h2', content: 'Gestionnaire de serveur (Server Manager)' },
          { type: 'p', content: 'Interface centrale de Windows Server. Permet d\'ajouter des rôles et fonctionnalités, surveiller les événements et gérer les services.' },
          { type: 'ul', items: [
            'Tableau de bord',
            'Serveur local',
            'Tous les serveurs',
            'Rôles installés',
          ]},
        ],
      },
      {
        id: 'active-directory',
        titre: 'Active Directory — Installation et Configuration',
        sections: [
          { type: 'h2', content: 'Qu\'est-ce qu\'Active Directory ?' },
          { type: 'p', content: 'Service d\'annuaire Microsoft qui centralise l\'authentification et la gestion des ressources réseau. Basé sur les protocoles LDAP et Kerberos.' },
          { type: 'table', headers: ['Objet', 'Description', 'Exemple'], rows: [
            ['Domaine',               'Unité administrative principale',         'tssr.local'],
            ['Forêt',                 'Ensemble de domaines liés',               'tssr.local + filiale.tssr.local'],
            ['OU (Unité d\'Org.)',    'Conteneur pour organiser les objets',     'OU=Informatique,DC=tssr,DC=local'],
            ['Utilisateur',           'Compte d\'accès',                         'anthony.agnolon@tssr.local'],
            ['Groupe',                'Collection d\'utilisateurs',               'GRP-Admins-IT'],
            ['GPO',                   'Stratégie de groupe',                      'Fond d\'écran imposé'],
          ]},
          { type: 'h2', content: 'Installer le rôle AD DS' },
          { type: 'steps', items: [
            { num: '1', title: 'Via Server Manager',                   content: 'Gérer → Ajouter des rôles → Active Directory Domain Services → Suivant jusqu\'à Installation.' },
            { num: '2', title: 'Via PowerShell',                       code: 'Install-WindowsFeature -Name AD-Domain-Services -IncludeManagementTools' },
            { num: '3', title: 'Promouvoir en contrôleur de domaine',  content: 'Cliquer sur le drapeau jaune dans Server Manager → Promouvoir ce serveur.' },
            { num: '4', title: 'Nouvelle forêt',                       content: 'Nom de domaine racine : <code>tssr.local</code>' },
            { num: '5', title: 'Niveau fonctionnel',                   content: 'Windows Server 2016 minimum recommandé.' },
            { num: '6', title: 'Mot de passe DSRM',                   content: 'Mode restauration des services d\'annuaire — à conserver précieusement.' },
            { num: '7', title: 'Redémarrage automatique',              content: 'Le serveur redémarre et devient contrôleur de domaine.' },
          ]},
          { type: 'h2', content: 'Gestion des utilisateurs (PowerShell)' },
          { type: 'code', content: '# Créer un utilisateur\nNew-ADUser -Name "Jean Dupont" -GivenName "Jean" -Surname "Dupont" `\n  -SamAccountName "j.dupont" -UserPrincipalName "j.dupont@tssr.local" `\n  -Path "OU=Utilisateurs,DC=tssr,DC=local" `\n  -AccountPassword (ConvertTo-SecureString "P@ssword123" -AsPlainText -Force) `\n  -Enabled $true\n\n# Lister tous les utilisateurs\nGet-ADUser -Filter * | Select-Object Name, SamAccountName, Enabled\n\n# Désactiver un compte\nDisable-ADAccount -Identity "j.dupont"\n\n# Réinitialiser un mot de passe\nSet-ADAccountPassword -Identity "j.dupont" -Reset `\n  -NewPassword (ConvertTo-SecureString "NewP@ss123" -AsPlainText -Force)' },
          { type: 'h2', content: 'Gestion des groupes' },
          { type: 'code', content: '# Créer un groupe\nNew-ADGroup -Name "GRP-Informatique" -GroupScope Global -GroupCategory Security `\n  -Path "OU=Groupes,DC=tssr,DC=local"\n\n# Ajouter un membre\nAdd-ADGroupMember -Identity "GRP-Informatique" -Members "j.dupont"\n\n# Lister les membres\nGet-ADGroupMember -Identity "GRP-Informatique"' },
          { type: 'h2', content: 'Gestion des Unités d\'Organisation' },
          { type: 'code', content: '# Créer une OU\nNew-ADOrganizationalUnit -Name "Informatique" -Path "DC=tssr,DC=local"\n\n# Lister les OUs\nGet-ADOrganizationalUnit -Filter * | Select-Object Name, DistinguishedName' },
          { type: 'h2', content: 'GPO — Stratégies de Groupe' },
          { type: 'p', content: 'Les GPO permettent d\'imposer des paramètres sur les utilisateurs et ordinateurs du domaine.' },
          { type: 'steps', items: [
            { num: '1', title: 'Ouvrir GPMC',            content: '<code>gpmc.msc</code> dans Exécuter (Win+R).' },
            { num: '2', title: 'Créer une GPO',           content: 'Clic droit sur l\'OU cible → Créer un objet GPO dans ce domaine.' },
            { num: '3', title: 'Modifier la GPO',         content: 'Clic droit → Modifier → Configuration utilisateur ou Configuration ordinateur.' },
            { num: '4', title: 'Exemples utiles',         content: 'Fond d\'écran imposé, désactiver les ports USB, mapper un lecteur réseau.' },
            { num: '5', title: 'Forcer l\'application',   code: 'gpupdate /force' },
          ]},
          { type: 'code', content: '# Voir les GPO appliquées sur un poste client\ngpresult /R\ngpresult /H rapport.html' },
        ],
      },
      {
        id: 'dns-dhcp',
        titre: 'DNS &amp; DHCP sur Windows Server',
        sections: [
          { type: 'h2', content: 'DNS — Domain Name System' },
          { type: 'p', content: 'Traduit les noms de domaine en adresses IP. Essentiel au fonctionnement d\'Active Directory.' },
          { type: 'table', headers: ['Type', 'Rôle', 'Exemple'], rows: [
            ['A',     'Nom → IPv4',               'srv01.tssr.local → 192.168.1.10'],
            ['AAAA',  'Nom → IPv6',               'srv01.tssr.local → ::1'],
            ['PTR',   'IPv4 → Nom (DNS inversé)', '192.168.1.10 → srv01.tssr.local'],
            ['MX',    'Serveur mail',              'tssr.local → mail.tssr.local'],
            ['CNAME', 'Alias',                     'www.tssr.local → srv-web.tssr.local'],
          ]},
          { type: 'code', content: '# Installer le rôle DNS\nInstall-WindowsFeature -Name DNS -IncludeManagementTools\n\n# Créer un enregistrement A\nAdd-DnsServerResourceRecordA -ZoneName "tssr.local" -Name "srv-web" -IPv4Address "192.168.1.20"\n\n# Vérifier la résolution\nResolve-DnsName srv-web.tssr.local\n\n# Vider le cache DNS\nClear-DnsServerCache' },
          { type: 'h2', content: 'DHCP — Dynamic Host Configuration Protocol' },
          { type: 'p', content: 'Attribue automatiquement les paramètres réseau aux clients : adresse IP, masque, passerelle, serveur DNS.' },
          { type: 'steps', items: [
            { num: '1', title: 'Installer le rôle DHCP',       code: 'Install-WindowsFeature -Name DHCP -IncludeManagementTools' },
            { num: '2', title: 'Autoriser le serveur dans AD',  code: 'Add-DhcpServerInDC -DnsName "srv01.tssr.local"' },
            { num: '3', title: 'Créer une étendue',             content: 'Définir la plage d\'adresses IP à distribuer aux clients.' },
            { num: '4', title: 'Configurer les options',        content: 'Passerelle (option 3), DNS (option 6), Domaine (option 15).' },
            { num: '5', title: 'Activer l\'étendue',            content: 'Mettre l\'étendue en état Actif pour commencer la distribution des baux.' },
          ]},
          { type: 'code', content: '# Créer une étendue DHCP\nAdd-DhcpServerv4Scope -Name "LAN-Principal" `\n  -StartRange 192.168.1.100 -EndRange 192.168.1.200 `\n  -SubnetMask 255.255.255.0 -State Active\n\n# Configurer les options\nSet-DhcpServerv4OptionValue -ScopeId 192.168.1.0 `\n  -Router 192.168.1.1 `\n  -DnsServer 192.168.1.10 `\n  -DnsDomain "tssr.local"\n\n# Voir les baux actifs\nGet-DhcpServerv4Lease -ScopeId 192.168.1.0' },
        ],
      },
    ],
    flashcards: [
      { id: 'f1',  recto: 'Quel port utilise LDAP ?',                              verso: 'Port 389 (LDAP) et 636 (LDAPS chiffré)' },
      { id: 'f2',  recto: 'Quel protocole utilise AD pour l\'authentification ?',  verso: 'Kerberos (port 88) — tickets d\'authentification chiffrés' },
      { id: 'f3',  recto: 'Commande pour forcer l\'application des GPO ?',          verso: 'gpupdate /force' },
      { id: 'f4',  recto: 'Qu\'est-ce qu\'une OU ?',                               verso: 'Unité d\'Organisation — conteneur AD pour organiser utilisateurs, groupes et ordinateurs' },
      { id: 'f5',  recto: 'Différence groupe Global vs Universel ?',               verso: 'Global : membres du même domaine. Universel : membres de toute la forêt.' },
      { id: 'f6',  recto: 'Commande PowerShell pour créer un utilisateur AD ?',    verso: 'New-ADUser -Name "Nom" -SamAccountName "login" -Enabled $true' },
      { id: 'f7',  recto: 'Qu\'est-ce que le DSRM ?',                              verso: 'Directory Services Restore Mode — mode de récupération du contrôleur de domaine' },
      { id: 'f8',  recto: 'Port utilisé par DNS ?',                                verso: 'Port 53 (UDP pour les requêtes, TCP pour les transferts de zone)' },
      { id: 'f9',  recto: 'Qu\'est-ce qu\'un enregistrement PTR ?',                verso: 'Enregistrement DNS inversé : IP → Nom (ex: 192.168.1.10 → srv01.tssr.local)' },
      { id: 'f10', recto: 'Port DHCP serveur et client ?',                         verso: 'Serveur : UDP 67 — Client : UDP 68' },
      { id: 'f11', recto: 'Les 4 étapes du processus DHCP ?',                      verso: 'DORA : Discover → Offer → Request → Acknowledge' },
      { id: 'f12', recto: 'Commande pour voir les GPO appliquées ?',               verso: 'gpresult /R (texte) ou gpresult /H rapport.html (HTML)' },
      { id: 'f13', recto: 'Qu\'est-ce qu\'une forêt AD ?',                         verso: 'Ensemble de domaines AD partageant un schéma commun et des relations d\'approbation' },
      { id: 'f14', recto: 'Commande pour promouvoir un serveur en DC ?',           verso: 'Install-ADDSForest (nouvelle forêt) ou Install-ADDSDomainController (domaine existant)' },
      { id: 'f15', recto: 'Quel outil graphique gère les GPO ?',                   verso: 'GPMC — Group Policy Management Console (gpmc.msc)' },
      { id: 'f16', recto: 'Commande pour joindre un PC au domaine ?',              verso: 'Add-Computer -DomainName "tssr.local" -Credential (Get-Credential) -Restart' },
      { id: 'f17', recto: 'Qu\'est-ce que le catalogue global AD ?',               verso: 'Serveur qui stocke une copie partielle de tous les objets de la forêt pour accélérer les recherches' },
      { id: 'f18', recto: 'Différence entre DNS primaire et secondaire ?',         verso: 'Primaire : zone en lecture/écriture. Secondaire : copie en lecture seule (redondance).' },
      { id: 'f19', recto: 'Commande pour lister les DCs du domaine ?',             verso: 'Get-ADDomainController -Filter *' },
      { id: 'f20', recto: 'Qu\'est-ce que Sysvol ?',                               verso: 'Dossier partagé sur tous les DCs contenant les scripts de connexion et les fichiers GPO' },
    ],
    qcm: [
      {
        id: 'q1',
        question: 'Quel est le port par défaut de LDAP ?',
        options: [
          { text: '389', correct: true  },
          { text: '443', correct: false },
          { text: '636', correct: false },
          { text: '88',  correct: false },
        ],
        explication: 'LDAP utilise le port 389. LDAPS (chiffré) utilise le port 636. Kerberos utilise le port 88.',
      },
      {
        id: 'q2',
        question: 'Quelle commande permet de forcer l\'application des GPO sur un client ?',
        options: [
          { text: 'gpedit /refresh', correct: false },
          { text: 'gpupdate /force', correct: true  },
          { text: 'gpresult /R',     correct: false },
          { text: 'gpmc /update',    correct: false },
        ],
        explication: 'gpupdate /force force la mise à jour immédiate de toutes les stratégies de groupe.',
      },
      {
        id: 'q3',
        question: 'Qu\'est-ce que DORA dans le contexte DHCP ?',
        options: [
          { text: 'Un protocole de sécurité',                             correct: false },
          { text: 'Les 4 étapes : Discover, Offer, Request, Acknowledge', correct: true  },
          { text: 'Un type de groupe AD',                                  correct: false },
          { text: 'Un rôle Windows Server',                                correct: false },
        ],
        explication: 'DORA décrit le processus d\'attribution d\'adresse IP : le client diffuse (Discover), le serveur propose (Offer), le client demande (Request), le serveur confirme (Acknowledge).',
      },
      {
        id: 'q4',
        question: 'Quelle édition de Windows Server 2025 permet des VMs illimitées ?',
        options: [
          { text: 'Standard',   correct: false },
          { text: 'Essentials', correct: false },
          { text: 'Datacenter', correct: true  },
          { text: 'Foundation', correct: false },
        ],
        explication: 'L\'édition Datacenter permet un nombre illimité de machines virtuelles. Standard en permet seulement 2.',
      },
      {
        id: 'q5',
        question: 'Quel protocole Active Directory gère l\'authentification ?',
        options: [
          { text: 'NTLM uniquement', correct: false },
          { text: 'Kerberos',        correct: true  },
          { text: 'RADIUS',          correct: false },
          { text: 'TACACS+',         correct: false },
        ],
        explication: 'Kerberos est le protocole d\'authentification principal d\'Active Directory depuis Windows 2000. Il utilise des tickets chiffrés.',
      },
      {
        id: 'q6',
        question: 'Quelle commande PowerShell crée une étendue DHCP ?',
        options: [
          { text: 'New-DhcpScope',         correct: false },
          { text: 'Add-DhcpServerv4Scope', correct: true  },
          { text: 'Create-DhcpRange',      correct: false },
          { text: 'Set-DhcpServerv4Scope', correct: false },
        ],
        explication: 'Add-DhcpServerv4Scope crée une nouvelle étendue DHCP IPv4 avec les paramètres de plage et de masque.',
      },
      {
        id: 'q7',
        question: 'Qu\'est-ce qu\'une OU dans Active Directory ?',
        options: [
          { text: 'Un type de serveur DNS',                    correct: false },
          { text: 'Un conteneur pour organiser les objets AD', correct: true  },
          { text: 'Un protocole d\'authentification',          correct: false },
          { text: 'Une stratégie de groupe',                   correct: false },
        ],
        explication: 'Une OU (Organizational Unit) est un conteneur qui permet d\'organiser les utilisateurs, groupes et ordinateurs dans AD, et d\'y appliquer des GPO ciblées.',
      },
      {
        id: 'q8',
        question: 'Sur quel port fonctionne DNS ?',
        options: [
          { text: 'Port 80',  correct: false },
          { text: 'Port 443', correct: false },
          { text: 'Port 53',  correct: true  },
          { text: 'Port 25',  correct: false },
        ],
        explication: 'DNS utilise le port 53 — UDP pour les requêtes standard, TCP pour les transferts de zone.',
      },
      {
        id: 'q9',
        question: 'Quelle commande joint un PC Windows au domaine tssr.local ?',
        options: [
          { text: 'Join-Domain -Name tssr.local',        correct: false },
          { text: 'Add-Computer -DomainName tssr.local', correct: true  },
          { text: 'Connect-Domain tssr.local',           correct: false },
          { text: 'Set-ADComputer -Domain tssr.local',   correct: false },
        ],
        explication: 'Add-Computer -DomainName "tssr.local" -Credential (Get-Credential) -Restart joint le PC au domaine et redémarre.',
      },
      {
        id: 'q10',
        question: 'Qu\'est-ce que Sysvol ?',
        options: [
          { text: 'Un service de sauvegarde AD',                              correct: false },
          { text: 'Le dossier partagé contenant les scripts et fichiers GPO', correct: true  },
          { text: 'Un protocole de réplication DNS',                          correct: false },
          { text: 'Un outil de monitoring AD',                                correct: false },
        ],
        explication: 'Sysvol est un dossier partagé répliqué sur tous les contrôleurs de domaine. Il contient les scripts de connexion et les modèles de stratégies de groupe.',
      },
    ],
  },
];
